### ISSUE TITLE
[Feature]: make a separate page for github 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#104]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/76370b54-8020-4b08-aa59-a894a3f10ad4)
just like we have a separate page for javascript in webd page make a separate page for github also

**Comment by 0-mayurkaretha** [comment]
Hello!
I would like to contribute, please assign me.

**Comment by pradeeptosarkar** [comment]
@0-mayurkaretha sure go ahead

**Comment by 0-mayurkaretha** [comment]
@pradeeptosarkar @mnnkhndlwl 
Hey!
Is these data available (as shown for separate Html page.) for Github page, Or do i need to put by myself?

pic1
![pic1](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/103996000/29d73b56-bf8f-4449-9453-f97f85635934)

pic2
![pic2](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/103996000/6333cf1c-6954-4c7d-865e-5dc81e1dec1f)

**Comment by pradeeptosarkar** [comment]
@0-mayurkaretha yeah you will have to put it yourself
