### ISSUE TITLE
[Feature]: make a separate page for nodejs

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#105]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/002a1095-e0b9-4253-a122-05b6873e2ebf)
just like we have a separate page for javascript and html make a separate page for nodejs

**Comment by IamSudhir-Kumar** [comment]
Assign this to me !
