### ISSUE TITLE
[Bug]: Static copyright year in footer

### ISSUE THREAD

**Issue by raunakgiri21** [NSCC-BPIT/NSCC-BPIT-Website#106]
### Describe the bug

The copyright year displayed in the footer has static value. In year 2024, it will keep displaying 2023, which is not good.  

### To Reproduce

1. Go to footer.
2. Check the copyright year. 
(Bug can be observed in code only for now unless we enter 2024)

### Expected Behavior

The year should change dynamically.

### Screenshot/ Video

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/53823257/becf8787-24d1-4560-8a24-f5d33ea8b875

### Additional context

I want to fix and make it dynamic.

**Comment by vamsi-spoidey7** [comment]
i would like to work on this issue

**Comment by pradeeptosarkar** [comment]
@raunakgiri21 sure go ahead

**Comment by pradeeptosarkar** [comment]
resolved
