### ISSUE TITLE
[Feature]: Create new page for Blockchain

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#108]
### Is your feature request related to a problem? Please describe.

from the resources page, on clicking on the blockchain card, the user must be directed to a new page for blockchain.
Take example from https://www.nsccbpit.tech/webd
the resources home page is at: https://www.nsccbpit.tech/resources

**Comment by Neel-07** [comment]
hello @pradeeptosarkar, can this issue be assigned to me.. would surely like to work on these

**Comment by pradeeptosarkar** [comment]
@Neel-07 sure go ahead

**Comment by ShivankK26** [comment]
would love to work

**Comment by pradeeptosarkar** [comment]
resolved
