### ISSUE TITLE
[Feature]: Create new cards for DSA, Cyber Security, UI/UX Designing

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#109]
### Is your feature request related to a problem? Please describe.

Add new cards on the resource page
1. DSA
2. Cyber Security
3. UI/UX Designing

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/a87c0b9f-c0be-40d2-a6fd-ed571fa2d792)

**Comment by SiddharthaKR** [comment]
Hi there, I'd be happy to look into the mentioned bug. Please assign this to me

**Comment by pradeeptosarkar** [comment]
@SiddharthaKR assigned to you

**Comment by KNagaHariKrishna** [comment]
can I work on this feature?

**Comment by pradeeptosarkar** [comment]
@SiddharthaKR are you still working on this issue?

**Comment by KNagaHariKrishna** [comment]
can I work on this feature?

**Comment by pradeeptosarkar** [comment]
@KNagaHariKrishna would you like to take it now?

**Comment by KNagaHariKrishna** [comment]
yes

**Comment by pradeeptosarkar** [comment]
@KNagaHariKrishna assigned

**Comment by pradeeptosarkar** [comment]
resolved

**Comment by KNagaHariKrishna** [comment]
if there are any other issues, please assign me.

**Comment by pradeeptosarkar** [comment]
@KNagaHariKrishna have a look at the unassigned issues https://github.com/NSCC-BPIT/NSCC-BPIT-Website/issues
