### ISSUE TITLE
[Bug]: Go-Back redirect button in 404 Page.

### ISSUE THREAD

**Issue by raunakgiri21** [NSCC-BPIT/NSCC-BPIT-Website#113]
### Describe the bug

On clicking the Go-Back Button in error 404 page, it redirects to home page instead of previous page.

### To Reproduce

1. Go to any page except home page.
2. Route to any invalid sub-route.

### Expected Behavior

The button should take back to previous page.

### Screenshot/ Video

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/53823257/a2f74818-bec7-4925-8f2d-f7d707d8cd1c

### Additional context

I want to fix this.

**Comment by pradeeptosarkar** [comment]
@raunakgiri21 assigned to you

**Comment by pradeeptosarkar** [comment]
resolved
