### ISSUE TITLE
[Feature]: Beautify the Programs Page 

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#116]
### Is your feature request related to a problem? Please describe.

The programs page at https://www.nsccbpit.tech/programs needs some beautification while staying aligned to the overall scheme of the project.

### Describe the solution you'd like

Any efforts which lead to a more friendly UX and better responsiveness are appreciated.

**Comment by yashthipsay** [comment]
Hi @pradeeptosarkar! Please assign me this issue to work on for hacktoberfest 2023.

**Comment by pradeeptosarkar** [comment]
sure @yashthipsay go ahead

**Comment by pradeeptosarkar** [comment]
@yashthipsay are you still working on this issue

**Comment by robo311** [comment]
Hi, is it possible to assign me this issue? I have experience in UI/UX design as well as in web development.

**Comment by pradeeptosarkar** [comment]
@robo311 would you like to take it?

**Comment by A1ya1** [comment]
Hello, can you assign this issue to me? I'm also a UI/UX designer...... I and @robo311 can both work on it

**Comment by pradeeptosarkar** [comment]
@robo311 @A1ya1 assigned to you guys

**Comment by robo311** [comment]
Thank you, I'll work on it asap

**Comment by A1ya1** [comment]
[Feature]: Beautify Program Pages.
![Frame 422](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/146150772/e97ee2d2-5aff-43b2-bd52-894d19af5702)
![Uploading Frame 421.png…]()
How is it?

**Comment by pradeeptosarkar** [comment]
@A1ya1 looks good

**Comment by A1ya1** [comment]
> @A1ya1 looks good

oh, okay......Here's the figma file for @robo311  or anyone who'd be developing it.........
https://www.figma.com/file/6qx1WnhWb4DMYDiLkyb3bj/Untitled?type=design&node-id=2%3A196&mode=design&t=8lWnoQH5nZvnV8E7-1

**Comment by pradeeptosarkar** [comment]
@robo311 are you still working on this issue?
