### ISSUE TITLE
[Bug]: The navbar looks ugly when scrolled down 

### ISSUE THREAD

**Issue by Dev-sAHSRAH** [NSCC-BPIT/NSCC-BPIT-Website#119]
### The navbar is not occupying complete width of the screen

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97530701/79fac8bb-6c80-4629-a994-4a2e2770848e)

As shown in the above image , the navbar is not occupying the complete width of the screen and hence making the image to be seen through.

I would like to improvise it along with making the overall navbar content to look better and properly aligned as shown below:
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97530701/a92d9ef1-2622-4c28-9546-42a8bde269f7)

Please assign this task to me as a part of hacktoberfest.
Thanks in advance

**Comment by mnnkhndlwl** [comment]
@Dev-sAHSRAH assigning you this issue

**Comment by pradeeptosarkar** [comment]
resolved. thanks for contributing @Dev-sAHSRAH
