### ISSUE TITLE
[Bug]: Need uniformity in the testimonials section

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#127]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/0dfe3fc7-759a-431c-b772-3f41ee4ba996)

the testimonials section is looking quite uneven. Any solution to this would be highly appreciated.!

**Comment by krishpatel023** [comment]
I'll fix this issue. Can you assign this to me?

**Comment by VishnuAmit** [comment]
Hey. I hope you are doing ok. I can fix this issue for you. Looking forward !

**Comment by pradeeptosarkar** [comment]
@krishpatel023 sure buddy go ahead. @VishnuAmit new issues will be opened soon :)

**Comment by VishnuAmit** [comment]
Yea. I am waiting !

**Comment by pradeeptosarkar** [comment]
resolved
