### ISSUE TITLE
[Feature]: Make the blog open in a new tab

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#131]

**Comment by mhdamaan79** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by pradeeptosarkar** [comment]
sure @mhdamaan79 go ahead. a quick merge would be highly appreciated

**Comment by pradeeptosarkar** [comment]
resolved, thanks for contributing @mhdamaan79
