### ISSUE TITLE
[Bug]: the "connect with us" button is not visible on mobile screens

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#132]
### Describe the bug

Desktop screen

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/be633edb-1293-46b8-9efa-34d5e2a8f1d4)

Mobile Screen

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/d639276c-3710-4b1c-ad66-efe0709bf28e)

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/45d98683-4ef9-43ab-98ae-1d79d311071e)

**Comment by Gauravtb2253** [comment]
I can work on it. Please assign me

**Comment by pradeeptosarkar** [comment]
@Gauravtb2253 assigned to you

**Comment by keshav39** [comment]
i am actually working on this right now and was about to ask for it to be assigned to me @pradeeptosarkar and then this happened

> @Gauravtb2253 assigned to you

**Comment by keshav39** [comment]
> i am actually working on this right now and was about to ask for it to be assigned to me @pradeeptosarkar and then this happened
> 
> > @Gauravtb2253 assigned to you

i have already identified the issue already and found another issue that the navbar in mobile view in the range of 700 to 900 width does not show any content in toggleable button

**Comment by pradeeptosarkar** [comment]
@Gauravtb2253 then pls don't move forward on this. closing this issue now. @keshav39 kindly raise a PR once you are done
