### ISSUE TITLE
[Bug]: Navbar dropdown menu not visible in tablet/ipad screen sizes

### ISSUE THREAD

**Issue by keshav39** [NSCC-BPIT/NSCC-BPIT-Website#135]
### Describe the bug

the dropdown menu of navbar in mobile view is not visible in 700 to 900 screen widths

### To Reproduce

- press ctrl+shift+I to open debug menu
- select toogle device toolbar
- then select responsive mode to change the width of device manually
- have the width between 700 and 900 to reproduce the issue

### Screenshot/ Video

# normal
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/9a492f9e-fa4c-46d5-9f9f-105e915b89ff)

# in 700 and 900 width
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/c60ebd54-578b-492e-bbce-fb36164e1ca4)

**Comment by keshav39** [comment]
assign me this

**Comment by pradeeptosarkar** [comment]
@keshav39 assigned

**Comment by pradeeptosarkar** [comment]
resolved
