### ISSUE TITLE
[Bug]: home page does not look good in bigger screens 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#142]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/ac8fd7af-1b1c-4031-be57-c502fcdc26a4)
it should look like below image
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/2205e82b-e08a-4bbc-b403-4f7aa504040e)

**Comment by devmusiczz** [comment]
@mnnkhndlwl can you assign it to me?

**Comment by mnnkhndlwl** [comment]
@devmusiczz assigned just make sure it should look good in all screens

**Comment by devmusiczz** [comment]
sure, I will try my best
