### ISSUE TITLE
[Feature]: add page for flutter 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#143]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/0a421114-f4cb-4ce8-b2dc-34025b038fb3)

**Comment by lazyMonk1010** [comment]
hey!! i would like to work on this issue !! do assign me this

**Comment by lazyMonk1010** [comment]
@mnnkhndlwl Please check the code for flutter component and merge my PR.

**Comment by pradeeptosarkar** [comment]
resolved
