### ISSUE TITLE
[Feature]: change android resource page remove java kotlin cross platfrom and add a page for react native

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#144]
### Is your feature request related to a problem? Please describe.

it should only be native , react native and flutter

**Comment by Rehan52004** [comment]
Please, assign me this issue.

**Comment by Rehan52004** [comment]
according to the title -
java
kotlin
cross plateform removed.
and react native added.

**Comment by pradeeptosarkar** [comment]
@Rehan52004 go ahead
