### ISSUE TITLE
[Bug]: HTML page localstorage has the same objects as JS page

### ISSUE THREAD

**Issue by vk-44** [NSCC-BPIT/NSCC-BPIT-Website#147]
### Describe the bug

The localstorage in the HTML has the exact replica of the JS localstorage page. Due to this, Clicking the checkboxes in HTML page does not set the state of the objects to true.

### To Reproduce

1) Go to resources page.
2) Click on Web Development.
3) Click on HTML.
4) Right Click and click on Inspect option from the dropdown.
5) Move to application tab.
6)Expand Local storage and click on "https://www.nsccbpit.tech".

### Expected Behavior

While clicking the checkboxes in the HTML page, The local sotrage object should set the state to "true"

### Screenshot/ Video

![Localstorage](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/51825472/2f69b68c-b29d-4b08-a02b-c0d79ee32680)

**Comment by mnnkhndlwl** [comment]
bro actually we are changing it from local storage to redux so that we can persist the information even if user reloads page and someone is already working on this

**Comment by vk-44** [comment]
No worries :)
