### ISSUE TITLE
[Bug]: Viewport Discrepancies in the repo 

### ISSUE THREAD

**Issue by pawas108ram** [NSCC-BPIT/NSCC-BPIT-Website#151]
### Describe the bug

The viewports that have been set are not correct and the styles are not getting applied properly .

### To Reproduce

Buggy ViewPort
![WhatsApp Image 2023-10-02 at 20 10 58](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/104372675/145ca425-1b81-4d4d-9131-d5baaa694d17)

### Expected Behavior

Expected
![WhatsApp Image 2023-10-02 at 20 10 20](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/104372675/b1e77c11-79eb-4f6a-b645-1fe5207fef41)

**Comment by pawas108ram** [comment]
I would like to take this issue

**Comment by TOLU-MICH** [comment]
Hi, please i would like to work on this issue

**Comment by pradeeptosarkar** [comment]
resolved

**Comment by keshav39** [comment]
@pawas108ram  this view port that u used in the issue

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/7d7b46f5-cf6e-40b4-bc7f-42fba8988f64)

is virtually impossible to achieve IRL
it can only be achieved by shrinking the tab in windows

also 

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/4b8d45d6-ab11-4202-8ff8-56a031e42c14)

this image has different viewport from the one above
