### ISSUE TITLE
[Bug]: Need to add active tabs

### ISSUE THREAD

**Issue by MadhuSaini22** [NSCC-BPIT/NSCC-BPIT-Website#153]
### Describe the bug

While exploring different tabs of website, was unable to see the current active tab. User experience can be improved by adding the active tab feature on the website.

### To Reproduce

Change the tabs from the header to website.

### Expected Behavior

Current active tab should be highlighted.

### Additional context

@Ritesh-Dabral I would love to work on this Issue.

**Comment by Ritesh-Dabral** [comment]
@MadhuSaini22 I am not the maintainer of this project 
@pradeeptosarkar kindly assist her

**Comment by pradeeptosarkar** [comment]
sure @MadhuSaini22 go ahead with your proposal
