### ISSUE TITLE
[Feature]: Redirect to home page on clicking the logo

### ISSUE THREAD

**Issue by Dev-sAHSRAH** [NSCC-BPIT/NSCC-BPIT-Website#154]
### Link homepage to page logo

As we see in all websites nowadays, the common practice is to reach the homepage by clicking on the logo.

I would like to remove the home tab in nav links and link the home page to the page logo.

Please assign me this issue as a part of hacktober fest.

**Comment by pradeeptosarkar** [comment]
sure @Dev-sAHSRAH go ahead buddy

**Comment by pradeeptosarkar** [comment]
resolved
