### ISSUE TITLE
[Bug]: projects page have footer mispositioned

### ISSUE THREAD

**Issue by MadhuSaini22** [NSCC-BPIT/NSCC-BPIT-Website#162]
### Describe the bug

In the projects page, footer is not it's position. Footer should be at the bottom of the page.

### To Reproduce

Go to projects page.

### Expected Behavior

It should be at the bottom of the page.

### Screenshot/ Video

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/81684710/5d06d49b-93df-426a-ab42-23b03ff97c25)

### Additional context

@pradeeptosarkar I would love to work on this.

**Comment by Aniketsahu28** [comment]
Hey, please assign this issue to me.  I can fix this issue

**Comment by pradeeptosarkar** [comment]
@MadhuSaini22 go ahead. @Aniketsahu28 we will open more issues soon bro
