### ISSUE TITLE
[Feature]: Add some resources to Web Development 

### ISSUE THREAD

**Issue by Petrosdevri** [NSCC-BPIT/NSCC-BPIT-Website#170]
### Describe the solution you'd like

I would like to add some resources to Web Development since I think the list for Frontend Developers is incomplete (we can add Bootstrap and Tailwind or SCSS in a list for CSS Frameworks and Preproccesors for example).

**Comment by Akshay9607** [comment]
hey, can i work on this issue ?

**Comment by pradeeptosarkar** [comment]
@Petrosdevri sure go ahead 
@Akshay9607 sorry bro @Petrosdevri raised this issue 😅

**Comment by Petrosdevri** [comment]
@Akshay9607 I have also raised another issue, do you want to take this one?

**Comment by Akshay9607** [comment]
> @Akshay9607 I have also raised another issue, do you want to take this one?

Yeah sure, you can assign that to me

**Comment by Petrosdevri** [comment]
Okay I have been unassigned, now wait for the administrator to assign you instead.

**Comment by pradeeptosarkar** [comment]
@Akshay9607 go ahead buddy

**Comment by pradeeptosarkar** [comment]
resolved
