### ISSUE TITLE
[Bug]: improve user experience

### ISSUE THREAD

**Issue by MadhuSaini22** [NSCC-BPIT/NSCC-BPIT-Website#171]
### Describe the bug

 -  In the navlinks, projects page is empty so we can keep that at the last link in the navbar. As the user changes it's tab first page(project) comes empty which looks bad, so we can put this navlink at the end.
 -  Secondly, in the resources page we can add hover animation on the cards which will improve the user experience.

### Expected Behavior

empty pages links should be at the end. And we can add an hover effect on resources cards.

### Additional context

@pradeeptosarkar I would love to work on this.

**Comment by mnnkhndlwl** [comment]
someone is assigned with the task to build projects page 
you can work on hover effect

**Comment by pradeeptosarkar** [comment]
ya @MadhuSaini22 you may proceed with the hover effects

**Comment by MadhuSaini22** [comment]
> ya @MadhuSaini22 you may proceed with the hover effects

Thanks
