### ISSUE TITLE
[Bug]: Responsiveness for laptops and tablet devices in the Web Development page

### ISSUE THREAD

**Issue by Petrosdevri** [NSCC-BPIT/NSCC-BPIT-Website#173]
### Describe the bug

When I try to view the page in my laptop I see that some sections are overflowing the space and cannot be viewed properly. Likewise, when I open the responsiveness page I see that the same happens to devices with a width of more than 800px. I would like to try 

### Screenshot/ Video

![Screenshot 2023-10-02 at 20-04-07 NSCC BPIT](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/100411628/925ef387-df27-4177-a10c-c569bd2bf9c1)
![Screenshot 2023-10-02 at 20-04-58 NSCC BPIT](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/100411628/98bf8466-a288-4f21-9bed-aa3d06697dcb)

**Comment by pradeeptosarkar** [comment]
sure @Petrosdevri go ahead
