### ISSUE TITLE
[Bug]:  Alignment in frontend framework page

### ISSUE THREAD

**Issue by Aniketsahu28** [NSCC-BPIT/NSCC-BPIT-Website#174]
### Describe the bug

The contents in the frontend framework page must be aligned.

### To Reproduce

1. Go to 'https://www.nsccbpit.tech'
2. Click on 'Resources'
3. Click on 'Web development'
4. Scroll down to 'Frontend development'
5. Click on 'frontend framework'
6. see error

### Expected Behavior

Content must be aligned properly in frontend framework page

### Screenshot/ Video

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97829838/c91bb033-17ef-4c7a-be72-9ecbc3f31269)

### Additional context

I would love to work on this

**Comment by pradeeptosarkar** [comment]
yup @Aniketsahu28 buddy go ahead
