### ISSUE TITLE
[Bug]: Contact Us Form: Data Not Clearing After Submission

### ISSUE THREAD

**Issue by saurav1207** [NSCC-BPIT/NSCC-BPIT-Website#177]
### Describe the bug

When using the contact us form on the website, I noticed that after submitting the form and receiving the success message, the data I entered in the form fields does not clear. The expected behavior is that after a successful submission, the form fields should reset or clear to allow for new input without manual clearing.

### To Reproduce

Navigate to the website.
Go to "Contact Us" section.
Fill out the contact form with any sample data, including name, email, message, etc.
Click the "Send" button.
Observe that a success message appears, indicating that the message has been sent successfully.
Observe that the data entered in the form fields remains intact, and the form is not cleared for new input.

### Expected Behavior

After submitting the form and receiving the success message, the form fields should automatically clear or reset, making it convenient for users to enter new information without having to manually clear the previous data.

### Screenshot/ Video

![Screenshot (799)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/93045673/630b7e6a-d649-4c04-b155-f613bb3bbb28)

**Comment by pradeeptosarkar** [comment]
yup @saurav1207 go ahead
