### ISSUE TITLE
[Feature]: Past event cards can have mouse pointer (UI/UX improvement)

### ISSUE THREAD

**Issue by Mithilesh-create** [NSCC-BPIT/NSCC-BPIT-Website#178]
### Is your feature request related to a problem? Please describe.

Past events can have pointer as it is appealing and can be future linked to blog after that particular event.

Before

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/68504882/8a93593d-1910-45d6-b4f3-242dbe3fc71e)

### Describe the solution you'd like

I would like to raise this issue as hacktoberfest pr for quality of life improvement. I request to assign this issue to me.

After

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/68504882/32ae631f-057f-4b49-8e46-d094614a5a41)

**Comment by pradeeptosarkar** [comment]
@Mithilesh-create can you please explain your solution

**Comment by Mithilesh-create** [comment]
Due to windows mouse cursor is hidden thats why i have to update the screenshot .

**Comment by pradeeptosarkar** [comment]
oh. okay go ahead @Mithilesh-create

**Comment by Mithilesh-create** [comment]
Thank You @pradeeptosarkar for assigning me this issue .

**Comment by pradeeptosarkar** [comment]
resolved. thanks for you contribution @Mithilesh-create
