### ISSUE TITLE
Broken Image Links on Blockchain page

### ISSUE THREAD

**Issue by Neel-07** [NSCC-BPIT/NSCC-BPIT-Website#179]
### Describe the bug

I have identified an issue with broken image links on a page I worked on previously. These images were functioning correctly, but I have noticed that they are no longer displaying as intended. I apologize for any inconvenience this may have caused, and I would like to rectify this mistake.

### To Reproduce

Go to the https://www.nsccbpit.tech/blockchain.
Scroll down to the section with the broken image links.
Observe that the images are not loading or displaying incorrectly.

### Expected Behavior

The images should load and display correctly as they did before.

### Screenshot/ Video

<img width="1040" alt="image" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/112561276/eeb3f2c7-ba86-47af-8d7d-3442d524679a">
The images are broken and not displaying as intended.

### Additional context

I would like to take responsibility for this issue and work on rectifying it. If possible, please assign this issue to me so that I can address it promptly.

**Comment by pradeeptosarkar** [comment]
@Neel-07 go ahead

**Comment by pradeeptosarkar** [comment]
resolved
