### ISSUE TITLE
[Feature]:  Create Kubernetes page Under DevOps

### ISSUE THREAD

**Issue by ghOst-vedant** [NSCC-BPIT/NSCC-BPIT-Website#180]
### Is your feature request related to a problem? Please describe.

it now shows 404

### Describe the solution you'd like

I can create the kubernetes page

**Comment by ghOst-vedant** [comment]
@pradeeptosarkar hey I'd like to complete this

**Comment by pradeeptosarkar** [comment]
@ghOst-vedant buddy go ahead

**Comment by ghOst-vedant** [comment]
@pradeeptosarkar  thank you

**Comment by ghOst-vedant** [comment]
@pradeeptosarkar a useer can be assign only 1 issue at a time

**Comment by pradeeptosarkar** [comment]
@ghOst-vedant if you want to work on something related to your existing assignment then no otherwise yeah

**Comment by ghOst-vedant** [comment]
@pradeeptosarkar  i could create more pages which aren't available rn

**Comment by pradeeptosarkar** [comment]
oh. then @ghOst-vedant create the issue which you want to work on as well.

**Comment by pradeeptosarkar** [comment]
@ghOst-vedant are you still working on this issue?

**Comment by ghOst-vedant** [comment]
@pradeeptosarkar yes within an hour ill create a pr

**Comment by pradeeptosarkar** [comment]
resolved
