### ISSUE TITLE
[Feature]: Create MongoDB page under Web development

### ISSUE THREAD

**Issue by ghOst-vedant** [NSCC-BPIT/NSCC-BPIT-Website#184]
### Describe the solution you'd like

I can create this page under Web development

**Comment by ghOst-vedant** [comment]
@mnnkhndlwl this one as well

**Comment by mnnkhndlwl** [comment]
bro work on your current assigned issues first

**Comment by ghOst-vedant** [comment]
these all are similar so it could have been good if was able to get these done.
no worries

**Comment by TaherAfsar** [comment]
Can I work on this issue?
