### ISSUE TITLE
[Bug]: Fix overall bugs in the application

### ISSUE THREAD

**Issue by vk-44** [NSCC-BPIT/NSCC-BPIT-Website#185]
### Describe the bug

1) The codebase contains JS reserved "class" instead of "className" in many files.
2) Attributes in SVG tags does not follow the naming convention. Ex: stroke-linecap, stroke-linejoin, stroke-width, etc...
3) Some map() methods missing the unique key index.

### To Reproduce

1) Run the code locally.
2) Open Inspect element and move to console tab.
3) Navigate around the application to see the errors.

### Screenshot/ Video

![err1](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/51825472/b6a0bdc4-3788-491c-98b3-24ce3d49b180)

![err2](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/51825472/bc5f1048-cd68-4e4c-8672-4aaa6c34da22)

**Comment by pradeeptosarkar** [comment]
resolved
