### ISSUE TITLE
[Bug]: active tab code is been merged but been discarded 

### ISSUE THREAD

**Issue by MadhuSaini22** [NSCC-BPIT/NSCC-BPIT-Website#186]
### Describe the bug

I've made a PR before an hour for active tab, but that code is been discarded because of some unexpected merge for some reason. So need to add it again.

### Additional context

@pradeeptosarkar I wanted to add it back, you can assign this to me.

**Comment by mnnkhndlwl** [comment]
post it on discussions and tag @pradeeptosarkar there
