### ISSUE TITLE
[Bug]: navbar is not at the center

### ISSUE THREAD

**Issue by MadhuSaini22** [NSCC-BPIT/NSCC-BPIT-Website#190]
### Describe the bug

Navbar's item menus are not at the center of header. The padding at both (upper & lower) side should be same.

### Screenshot/ Video

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/81684710/39f0e5f5-14c8-4cf8-888d-3a12812ae1f5)

### Additional context

@pradeeptosarkar Would love to work on.

**Comment by pradeeptosarkar** [comment]
yeah go ahead @MadhuSaini22
