### ISSUE TITLE
[Bug]: The logo disappear in small sizes and there is no hover effect in navigation bar

### ISSUE THREAD

**Issue by dev-abhishekkr** [NSCC-BPIT/NSCC-BPIT-Website#193]
### Describe the bug

There is no hover effect in the navigation bar header and also the company logo disappears on small window as we inspect.

I can add and fix this, please assign me this issue.

### To Reproduce

inspect and decrease the screen size, hover over the nav-links: there is no hover effect

### Screenshot/ Video

![Screenshot (115)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/144001779/e5966a52-10fb-4585-880b-05375d2326e9)
![Screenshot (116)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/144001779/aef1f62b-da87-42d8-a217-878b4c0533a5)

**Comment by Musak2** [comment]
can i work on this? :)

**Comment by pradeeptosarkar** [comment]
@dev-abhishekkr @Musak2 someone is already working on a similar issue so closing this one

**Comment by keshav39** [comment]
is this issue not yet resolved? @pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
@keshav39 ig no, this issue is still remaining

**Comment by a-s-t-e-y-a** [comment]
@pradeeptosarkar can you assign this issue to me

**Comment by a-s-t-e-y-a** [comment]
@pradeeptosarkar Please review my PR

**Comment by pradeeptosarkar** [comment]
@dev-abhishekkr @a-s-t-e-y-a both of your prs have merge conflicts

**Comment by pradeeptosarkar** [comment]
@dev-abhishekkr since you opened the bug report, assigned to you.

**Comment by pradeeptosarkar** [comment]
closing this now

**Comment by a-s-t-e-y-a** [comment]
@a-s-t-e-y-a can you assign this to me
