### ISSUE TITLE
[Feature]: Change color of navlinks while 'hovering' and  on 'active' , also give shadow to 'contact with us' button on hover.

### ISSUE THREAD

**Issue by Aniketsahu28** [NSCC-BPIT/NSCC-BPIT-Website#194]
### Is your feature request related to a problem? Please describe.

I sometimes get confuse to identify which page is open because the nav Links are same on active or inactive.

### Describe the solution you'd like

Color of navLinks should be change on hover and while the page is active.
'Contact with us' button should be given box shadow on hover to good look.

### Additional context

I would love to work on this.

**Comment by Aniketsahu28** [comment]
@pradeeptosarkar @mnnkhndlwl  can I take this issue ?

**Comment by pradeeptosarkar** [comment]
@Aniketsahu28 go ahead
