### ISSUE TITLE
[Feature]: make a separate page for computer vision

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#196]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/3e2bf044-ac87-4c2a-8440-cf1c1c286863)

**Comment by Tarctic** [comment]
I can try and work on this! Could you assign it to me?

**Comment by Tarctic** [comment]
@mnnkhndlwl Is it possible to send me the code of https://www.nsccbpit.tech/webd so I can use it as inspiration? I can work on it on my own, however, I want it to be as consistent with the page design as possible.

**Comment by Rehan52004** [comment]
It is very easy task, I want to work on it.
Please assign to me.

**Comment by Tarctic** [comment]
@mnnkhndlwl you may assign it to @Rehan52004 if you wish, as I won't be able to do this until after a few days. Thanks for understanding 🙂

**Comment by mnnkhndlwl** [comment]
@Rehan52004 do you want to work on this issue

**Comment by Rehan52004** [comment]
Yes

**Comment by pradeeptosarkar** [comment]
@Rehan52004 you may go ahead buddy
