### ISSUE TITLE
[Feature]: make a separate page for deep learning

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#197]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/fe3e21a4-0d35-49ab-91c1-825a1ebafa3b)

**Comment by Gauravtb2253** [comment]
I would like to work on this. Please assign me.

**Comment by pradeeptosarkar** [comment]
resolved. thanks for contributing @Gauravtb2253
