### ISSUE TITLE
[Feature]: add other option in cloud section of devops page and a separate page for aws

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#198]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/7799492f-e921-4a61-9a16-667b53ad4d13)
currently it only has aws add other options such as azure and google cloud

**Comment by Akshay9607** [comment]
hey, i would like to work on this feature, can you assign this to me please ?

**Comment by pradeeptosarkar** [comment]
@Akshay9607 are you still working on this issue?
