### ISSUE TITLE
[Bug]: remove tailwind and bootstrap from frontend frameworks page and add them to css frameworks

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#202]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/761042fc-c321-4438-ab3c-e92bae6ae5bb)
also remove material ui and chakra ui from that page

**Comment by LOGESH-B** [comment]
Hii @mnnkhndlwl 
Can i get assigned?

**Comment by pradeeptosarkar** [comment]
@LOGESH-B go ahead

**Comment by pradeeptosarkar** [comment]
resolved
