### ISSUE TITLE
[Feature]: Create dedicated page for cybersecurity

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#211]
### Is your feature request related to a problem? Please describe.

Need a separate page for cybersecurity. Inspiration can be taken from Web Development and AI/ML Pages. 
The resources page: https://www.nsccbpit.tech/resources

**Comment by bibaswan7** [comment]
Let me complete this assignment

**Comment by bibaswan7** [comment]
do I put the content on my own? or you going to provide me some materials?

**Comment by pradeeptosarkar** [comment]
@bibaswan7 yeah you will need to put the content on your own. you may refer tha other domain pages to understand what all needs to be put. let me know whether I should assign to you or not

**Comment by bibaswan7** [comment]
Please do assign it to me. I will complete all of them

**Comment by pradeeptosarkar** [comment]
@bibaswan7 done

**Comment by pradeeptosarkar** [comment]
@bibaswan7 are you still working on it?

**Comment by bibaswan7** [comment]
Yes I will make a PR by today

**Comment by mnnkhndlwl** [comment]
@bibaswan7 are you still working on this issue

**Comment by bibaswan7** [comment]
Yes I am almost done, will make a PR in next 1 hour

**Comment by pradeeptosarkar** [comment]
resolved
