### ISSUE TITLE
[Feature]: Create dedicated page for UI/UX Designing

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#212]
### Is your feature request related to a problem? Please describe.

Need a separate page for UI/UX Designing. Inspiration can be taken from Web Development and AI/ML Pages. 
The resources page: https://www.nsccbpit.tech/resources

**Comment by robo311** [comment]
Hi I would like to get assigned this issue. What should be included in the page?

**Comment by bibaswan7** [comment]
Assign me this task. I will just find the content on my own.

**Comment by pradeeptosarkar** [comment]
@robo311 you would need to include the necessary stuff/resources one needs to learn to become expert in ui/ux

**Comment by robo311** [comment]
Alright, I'll look into it and start working on it.

**Comment by pradeeptosarkar** [comment]
@robo311 are you still working on this issue?

**Comment by pradeeptosarkar** [comment]
@TaherAfsar would you like to work on this issue now?

**Comment by TaherAfsar** [comment]
Yes

**Comment by pradeeptosarkar** [comment]
@TaherAfsar sure go ahead
