### ISSUE TITLE
[Bug]: Pages load with same scroll as previous page

### ISSUE THREAD

**Issue by keshav39** [NSCC-BPIT/NSCC-BPIT-Website#214]
### Describe the bug

whenever we click on a link or redirect to another page, the page does not load from the top but from wherever the scrollbar was previously. this behavior is expected to be a feature only in the resource page while we are clicking on the different cards and but not in every other page.

### Expected Behavior

when clicking on lets say UI/UX design Card and it shows 404 page not found. we then click on go back to home button and see it scroll back to UI/UX. This should only happen in resource page.
every where else should take us back to the top of the page.

### Screenshot/ Video

# this behavior oh resource page is alright

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/f246b7b6-e5cb-4af7-b6fe-7ca2721cbbb1

# this is not as it continues from the bottom

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/13dbad89-7808-4676-bca6-05e713738588

**Comment by keshav39** [comment]
just found the issue and raised it as a bug, do not assign me this

**Comment by bibaswan7** [comment]
Assign me the task. I can fix the problem

**Comment by pradeeptosarkar** [comment]
resolved
