### ISSUE TITLE
[Bug]: Multiple footers on CSS page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#217]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/b31a4f15-846b-458d-8720-10db563d5ad2)

https://www.nsccbpit.tech/css

multiple footers are appearing on the CSS page

**Comment by a-s-t-e-y-a** [comment]
@pradeeptosarkar can you assign this issue to me
