### ISSUE TITLE
[Feature]: Uneven heights of the domain cards

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#221]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/41ad811c-4f85-4840-a366-c3b6f8c7c8ad)

the domain specific cards currently have heights not uniform across the page. for eg the heights of cards on row no. 2 is different from those on row no. 3

**Comment by peeplika** [comment]
can you assign it to me?

**Comment by pradeeptosarkar** [comment]
@peeplika go ahead. @Mridul2820 buddy we will opening more issues soon :)

**Comment by pradeeptosarkar** [comment]
@peeplika are you still working on this?

**Comment by peeplika** [comment]
Yes , I'm new to open source . I've been working on this issue, but I'm facing some challenges . Would it be possible for you to assign this issue to someone else or provide some advice on how to proceed?

**Comment by pradeeptosarkar** [comment]
yeah sure @peeplika I can assign to someone else. and for help regarding contributions please have a look at the read me of this repo as well as the CONTRIBUTION.md file. It will help you

**Comment by pradeeptosarkar** [comment]
@Mridul2820 would you like to take it?

**Comment by tamago01** [comment]
I could do this too

**Comment by pradeeptosarkar** [comment]
sure @tamago01 go ahead
