### ISSUE TITLE
[Feature]: introduce a little interactivity to the teams page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#222]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/81fd4e5e-3238-40c2-b7c4-54e592ac458b)

currently the teams card is static. the only interaction is with the links on each card which have a hover effect.

Any effort on beautifying this page or increasing the interactivity is welcome

**Comment by Rhythm-08** [comment]
Hello I would like to work on this issue

**Comment by Noazs** [comment]
Hello, can i work on this?

**Comment by pradeeptosarkar** [comment]
resolved
