### ISSUE TITLE
[Feature]: Add card for express and firebase in backend development

### ISSUE THREAD

**Issue by Aniketsahu28** [NSCC-BPIT/NSCC-BPIT-Website#241]
### Describe the solution you'd like

Make card for express and firebase in backend development

### Additional context

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97829838/456372ca-3d73-4e76-b250-336ec069259d)

**Comment by Aniketsahu28** [comment]
Hey @pradeeptosarkar i would like on this feature

**Comment by pradeeptosarkar** [comment]
go ahead @Aniketsahu28
