### ISSUE TITLE
[Bug]: programs section is not properly responsive in tab view & medium view

### ISSUE THREAD

**Issue by AnishTiwari16** [NSCC-BPIT/NSCC-BPIT-Website#252]
### Describe the bug

the program screen is not responsive the content and image are not taking enough space and outer div does not have appropriate styling 

### To Reproduce

go to program route and view it on tab view

### Screenshot/ Video

<img width="536" alt="Screenshot 2023-10-04 at 3 00 36 AM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/87610940/83f55945-d45c-41b6-94c7-adf0f66aa5e7">

**Comment by AnishTiwari16** [comment]
will fix it please assign it to me!

**Comment by mnnkhndlwl** [comment]
someone is already working on programs page
