### ISSUE TITLE
[Bug]: On the Mobile screen, in the home page below this "Few good words about us!" section the text content is not displaying properly

### ISSUE THREAD

**Issue by KNagaHariKrishna** [NSCC-BPIT/NSCC-BPIT-Website#264]
### Describe the bug

On the Mobile screen, in the home page below this "Few good words about us!" section the text content is not displaying properly

### Expected Behavior

the text should display properly 

### Screenshot/ Video

![Screenshot 2023-10-04 221355](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/122369350/567fb1a3-b911-40ae-ba9f-26db2cd93e68)

**Comment by mnnkhndlwl** [comment]
can you please elaborate what would you do

**Comment by KNagaHariKrishna** [comment]
hear text is hiding and not showing the entire text, that is why I have made the entire text visible and readable.

**Comment by pradeeptosarkar** [comment]
resolved
