### ISSUE TITLE
[Bug]: on the AI/ML resources main page there are multiple repetitive cards. Need to remove them

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#271]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/5440bcb4-2def-4a2f-9588-9472245f5969)

on the AI/ML resources main page there are multiple repetitive cards. Need to remove them.

Remove the cards which appear twice. keep only four cards in the "ai/ml domain" section: NLP, Computer vision, reinforcement learning, deep learning. Remove data science as we have a dedicated page for it.

**Comment by omriattiya** [comment]
can you assign this issue to me?

**Comment by pradeeptosarkar** [comment]
resolved
