### ISSUE TITLE
[Bug]: Readability on the data science page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#272]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/964425c2-331c-49f0-8d60-6cfa23116bc5)

The text is not much readable

**Comment by omriattiya** [comment]
hi, can you assign this to me?

**Comment by pradeeptosarkar** [comment]
sure buddy go ahead

**Comment by pradeeptosarkar** [comment]
resolved
