### ISSUE TITLE
[Feature]: Build the Projects Page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#275]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/4223c0cd-4391-4060-bae8-a37422c1cc52)

We have a dedicated projects page. In this we wish to showcase the projects made by our community members and display details such as:

Project Name
Deployment link
Github link etc

Someone needs to create the template for this page and insert dummy cards, which can be later updated with actual projects. Please ensure the color and theme matches rest of the website

**Comment by Gaurav-Borah** [comment]
please assign this to me.

**Comment by pradeeptosarkar** [comment]
@Gaurav-Borah sure go ahead. feel free to tag in case of doubts

**Comment by iamrishiksahu** [comment]
@pradeeptosarkar I am interested in working on this issue, I will be doing this today itself. 

I will add:

1. Project cards with dummy images and data.
2. Filter and search functionality that will be beneficial in improving the user experience.

If I am assigned to this, I would start the implementation immediately. I request you to kindly assign.

**Comment by mnnkhndlwl** [comment]
@iamrishiksahu it's already assigned to @Gaurav-Borah

**Comment by Gaurav-Borah** [comment]
If I don't deliver this within 24 hours feel free to take this from me @iamrishiksahu.

**Comment by pradeeptosarkar** [comment]
resolved
