### ISSUE TITLE
[Bug]: Alignment issue in the vertical timeline top 2 cards

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#277]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/b7f715f0-1db8-4b53-a565-8f40bc2c160f)

The top 2 cards' content is left aligned while it should be center-aligned like the rest of the cards.!

**Comment by ronisarkarexe** [comment]
@pradeeptosarkar can you please assign me

**Comment by ronisarkarexe** [comment]
@pradeeptosarkar this task also.

**Comment by pradeeptosarkar** [comment]
sure @ronisarkarexe go ahead :)

**Comment by pradeeptosarkar** [comment]
resolved
