### ISSUE TITLE
[Feature]: Insert sub domains on data science page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#279]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/6d403698-2fe6-44ed-893e-b12fd03e84f1)

https://www.nsccbpit.tech/dataScience

In the data science main page currently no sub domains are there. For other domains such as web and ai/ml sub-domains are mentioned in those pages

add all the subdomains, tools and technologies needed to learn data science. Inspiration can be taken from other domains' pages.

**Comment by tamago01** [comment]
I could do this. @pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
resolved
