### ISSUE TITLE
[Bug]: Android development page Heading left alligned

### ISSUE THREAD

**Issue by ghOst-vedant** [NSCC-BPIT/NSCC-BPIT-Website#287]
### Describe the bug

The title has to be in center but it is at the left

### To Reproduce

got to 
1. Resources Page
2. Android Development page

### Expected Behavior

<img width="1671" alt="Screenshot 2023-10-05 at 7 36 40 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/71282147/f74c5779-ea33-4ffc-8d3c-b631408c93a7">

### Screenshot/ Video

<img width="1634" alt="Screenshot 2023-10-05 at 7 36 29 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/71282147/b616db54-33ad-4791-a2f7-6d49a0bc8d9b">

**Comment by ghOst-vedant** [comment]
i can complete this @pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
go ahead @ghOst-vedant

**Comment by pradeeptosarkar** [comment]
resolved
