### ISSUE TITLE
[Bug]: Home page mobile screen issue

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#288]
### Describe the bug

![WhatsApp Image 2023-10-05 at 20 42 57_b60df3ed](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/34af9354-0f8f-465f-bf00-59a36ff74977)

The words: "Newton School", "Coding Club" and "Bhagwan Parshuram Institute of Technology", all should be centered aligned.

its working fine for all sizes above width 510 px (centered) and above 1400px (left aligned)

only when the screen width becomes less than 510 px, does this issue arise.

**Comment by pradeeptosarkar** [comment]
@Darkhood148 go ahead. @NsCracker we will open more issues you may contribute in them buddy :)

**Comment by Darkhood148** [comment]
@pradeeptosarkar I have raised the PR. Please review #292
