### ISSUE TITLE
[Bug]: Projects page is not responsive at smaller screen size

### ISSUE THREAD

**Issue by Tanush-J** [NSCC-BPIT/NSCC-BPIT-Website#298]
### Describe the bug

The projects page is not responsive for the dimensions of Galaxy Fold and some other small screen sizes, and images are not visible at this size content should also be in column form instead of row.

I would like to work on this please assign me this.

### Expected Behavior

Content should be responsive.

### Screenshot/ Video

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75922615/61378d4b-d50f-444b-b5f7-a6dedf85b35f

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75922615/a4140b0e-8b2f-4702-8c6d-c64a8f6b1241

**Comment by pradeeptosarkar** [comment]
@Tanush-J sure go ahead

**Comment by pradeeptosarkar** [comment]
@Tanush-J are you still working on this issue

**Comment by Tanush-J** [comment]
Yeah, I am almost done

**Comment by pradeeptosarkar** [comment]
resolved
