### ISSUE TITLE
[Feature]: Dedicated page for virtual reality

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#304]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/3ce91207-a6d2-4480-8d6a-323e08f8931c)

https://www.nsccbpit.tech/arvr/virtual-reality

Add content to this page.!
Inspiration can be taken from other sub-domain pages.!

**Comment by nikhilgarg26** [comment]
hey @pradeeptosarkar can you please assign me this issue ?

**Comment by pradeeptosarkar** [comment]
@nikhilgarg26 we need content on this page related so virtual reality. like other web development subdomains

**Comment by nikhilgarg26** [comment]
thanks for the reference can assign this issue, so that i can start working on it

**Comment by nikhilgarg26** [comment]
thanks for assigning i would give an update soon

**Comment by pradeeptosarkar** [comment]
resolved
