### ISSUE TITLE
[Feature]: Dedicated page for WebXR

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#307]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/a34ea2a3-6a65-4724-99bc-719aa816f94e)

https://www.nsccbpit.tech/arvr/webXR

Add content to this page.!
Inspiration can be taken from other sub-domain pages.!

**Comment by nikhilgarg26** [comment]
@pradeeptosarkar can you assign this issue so that i can start working

**Comment by pradeeptosarkar** [comment]
resolved
