### ISSUE TITLE
[Bug]: Mobile Screen Homepage Issue

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#308]
### Describe the bug

![WhatsApp Image 2023-10-06 at 14 29 15_ed61936a](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/1ce046da-8ce1-4304-9843-da89e80a96fb)

The "Coding Club" should be center aligned on small screen devices

**Comment by Krishnakalani111** [comment]
I could take over this, could you assign this to me under hactoberfest

**Comment by pradeeptosarkar** [comment]
sure @Krishnakalani111 go ahead

**Comment by pradeeptosarkar** [comment]
resolved
