### ISSUE TITLE
[Feature]: Projects Page detailing

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#309]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/2f501f5b-530a-470f-8697-cc942ddc0763)

In the projects page, we need to have more details such as the owner of the project, tech stack used, deployment link and github repo link

**Comment by Panth1823** [comment]
heyy i think i can work on this issue can u assign it to me?

**Comment by mnnkhndlwl** [comment]
@Panth1823 assigned to you

**Comment by pradeeptosarkar** [comment]
@Panth1823 are you still working on this issue?

**Comment by Panth1823** [comment]
@pradeeptosarkar I'm currently unable to work on this issue due to some prior commitments. Could you please assign it to someone else who is available to handle it at the moment?

**Comment by pradeeptosarkar** [comment]
@Panth1823 no worries

**Comment by Tanush-J** [comment]
I would like to give this a try

**Comment by Tanush-J** [comment]
Current main branch doesn't refect the changes I made for issue #330 can you fix these @pradeeptosarkar @mnnkhndlwl

**Comment by Tanush-J** [comment]
currently the projects card already has techstack used and github link. So, I will add owner of project and deployment link. Is there anything else I should add?

**Comment by pradeeptosarkar** [comment]
yup this will work @Tanush-J

**Comment by pradeeptosarkar** [comment]
resolved
