### ISSUE TITLE
[Bug]: Footer displayed twice

### ISSUE THREAD

**Issue by nikhilgarg26** [NSCC-BPIT/NSCC-BPIT-Website#311]
### Describe the bug

the footer in the [https://www.nsccbpit.tech/mongodb](https://www.nsccbpit.tech/mongodb) is displayed twice.

### To Reproduce

Go to 'https://www.nsccbpit.tech/mongodb'

### Screenshot/ Video

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/116938919/fc7ab78d-350d-46c7-95f5-d63106ca63a3)

**Comment by nikhilgarg26** [comment]
can you please add essential labels and assign it

**Comment by pradeeptosarkar** [comment]
@nikhilgarg26 go ahead
