### ISSUE TITLE
[Feature]: make a separate page for figma under ui/ux 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#318]

**Comment by GyanPrakashRaj** [comment]
!assign it to me

**Comment by pradeeptosarkar** [comment]
@GyanPrakashRaj go ahead

**Comment by GyanPrakashRaj** [comment]
> @GyanPrakashRaj go ahead

On the way ▶️

**Comment by Rehan52004** [comment]
Is this issue still open, i want to work on it. pLeae assign to me.

**Comment by pradeeptosarkar** [comment]
@GyanPrakashRaj are you still working on it?

**Comment by GyanPrakashRaj** [comment]
> @GyanPrakashRaj are you still working on it?

Sorry
Refer it to someone else

**Comment by pradeeptosarkar** [comment]
@Rehan52004 assigned to you
