### ISSUE TITLE
[Feature]: Beautify resources page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#319]
### Is your feature request related to a problem? Please describe.

change the current theme of the resources page you can take inspiration from programs page and teams page

**Comment by GyanPrakashRaj** [comment]
!assign it to me.

Solution approach
- I will try to implement a different UI for the Resources section

additionally 
- before sending PR I'll send it here for review.

**Comment by mnnkhndlwl** [comment]
@GyanPrakashRaj just make sure everything to implement in ui is responsive

**Comment by GyanPrakashRaj** [comment]
> @GyanPrakashRaj just make sure everything to implement in ui is responsive

Sure 👾

**Comment by GyanPrakashRaj** [comment]
> @GyanPrakashRaj are you still working on this

Yes, I'm still working
Sorry for late ... some academic issues are in my room right now... will push the PR soon

**Comment by tamago01** [comment]
I could do this too

**Comment by pradeeptosarkar** [comment]
@GyanPrakashRaj are you still working on this issue?

**Comment by GyanPrakashRaj** [comment]
> @GyanPrakashRaj are you still working on this issue?

Im stuck in my academics 
Sorry for inconvenience
Kindly assign it to someone else

**Comment by mnnkhndlwl** [comment]
@tamago01 assigning you this issue
