### ISSUE TITLE
[Bug]: Duplicated Footer in UI/UX Section of Resources

### ISSUE THREAD

**Issue by tiwari00ayush** [NSCC-BPIT/NSCC-BPIT-Website#321]
### Describe the bug

When navigating to the "UI/UX" section under "Resources" on the project's website, I noticed that the footer at the bottom of the page is duplicated.

### To Reproduce

1. Go to the project's website.
2. Navigate to the "Resources" section.
3. Click on the "UI/UX" section.
4. Scroll down to the bottom.

### Expected Behavior

I expected to see a single, consistent footer at the bottom of the page.

### Screenshot/ Video

<img width="1440" alt="Screenshot 2023-10-07 at 10 19 59 AM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/107319179/b1cb84aa-804f-4a3e-97b4-0ace45c80507">

**Comment by tiwari00ayush** [comment]
@pradeeptosarkar can you assign this issue to me

**Comment by mnnkhndlwl** [comment]
@tiwari00ayush this issue is also present in other pages so we will handle this issue after hactoberfest

**Comment by mnnkhndlwl** [comment]
you  can take a look on other issues
