### ISSUE TITLE
[Feature]: Makeover of the social media section

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#331]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/b75ceed0-2bf4-49e4-897d-f813e7122d85)

Currently the social media section has only 3 youtube videos.  But we have many social handles. We would like to have atleast 4 social media widgets on this section

Therefore we invite anyone who can give this section a transformative makeover to build this section.

Our social handles can be found at: linktr.ee/nscc_bpit

**Comment by Pr0-C0der** [comment]
Hey, assign this issue to me. BTW where do you want the social media widgets to be?

**Comment by pradeeptosarkar** [comment]
@Pr0-C0der go ahead

basically below the "Social Media Pulse" title, we want to embed our twitter feed/last tweet, insta feed/last post, hashnode blog as well as yt feed/last video

the changes can be done in the "SocialMedia.jsx" file

**Comment by Neel-07** [comment]
Hello @pradeeptosarkar can this issue be assigned to me i would like to work on it.

**Comment by pradeeptosarkar** [comment]
@Pr0-C0der are you working on it?

**Comment by Pr0-C0der** [comment]
Sorry! @pradeeptosarkar  I am unable to solve it. please assign it to @Neel-07 .

**Comment by pradeeptosarkar** [comment]
@Neel-07 would you like to take it?

**Comment by Neel-07** [comment]
yes sure @pradeeptosarkar, you can assign it to me. If i need further assistance do help me out.

**Comment by pradeeptosarkar** [comment]
go ahead @Neel-07

**Comment by tamago01** [comment]
I can do this too

**Comment by pradeeptosarkar** [comment]
@Neel-07 are you still working on this issue?

**Comment by Rehan52004** [comment]
I want to work on this issue, please assign to me.

**Comment by pradeeptosarkar** [comment]
we are closing this issue as of now
