### ISSUE TITLE
[Feature]: Update Twitter icon on Responsive Cards

### ISSUE THREAD

**Issue by pragyamishra56** [NSCC-BPIT/NSCC-BPIT-Website#336]
### Is your feature request related to a problem? Please describe.

**Problem Description:**
The current Twitter icon used on responsive cards is outdated and does not align with the design or user expectations. This icon may cause confusion or frustration among users as it fails to convey the modern look and feel associated with Twitter. To enhance the user experience and maintain design consistency, we propose updating the Twitter icon used on responsive cards.

### Describe the solution you'd like

**Proposed Solution:**
We recommend replacing the existing Twitter icon with a more contemporary and recognizable version. This updated icon should reflect the latest design trends and the official Twitter branding to ensure that users immediately associate it with Twitter. By making this change, we aim to improve the overall aesthetics and usability of responsive cards, making them more engaging and user-friendly.

### Describe alternatives you've considered

**Benefits:**

Improved User Experience: A modern Twitter icon will make it easier for users to identify and interact with Twitter content on responsive cards.
Design Consistency: Ensuring that the Twitter icon matches the official branding helps maintain a cohesive and professional appearance.
Enhanced Engagement: A refreshed icon can attract more attention and encourage users to click on Twitter-related content, potentially increasing engagement rates.

### Additional context

**Implementation Details:**

Identify the latest official Twitter icon provided by Twitter's brand guidelines.
Replace the existing Twitter icon on responsive cards with the updated version.
Ensure that the new icon is appropriately sized and positioned to maintain card aesthetics.
Test the updated responsive cards across various devices and screen sizes to ensure responsiveness and compatibility.

![Screenshot 2023-10-09 224700](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/115208912/f9b6614e-8bb6-4316-b1e6-432c13912605)

**Comment by pragyamishra56** [comment]
I hope you're doing well. Pragya Mishra, working as a Front-end developer and I'm excited about this project. This would be my first time hacktoberfest2023 contribution to an open-source project, and I'm eager to get started.
I've been looking through the issues and I'm particularly drawn to this issue. It seems like a great start for me to learn and contribute to this project.
Could I take on this issue? I'm more than willing to put in the effort and would greatly appreciate your guidance on how to proceed.
Thanks a lot for your time and consideration!

**Comment by pradeeptosarkar** [comment]
@pragyamishra56 sure buddy go ahead

**Comment by Rehan52004** [comment]
i want to work on it, please assign to me.

**Comment by pragyamishra56** [comment]
@pradeeptosarkar Thank you so much Sir currently I'm working on it Sir

**Comment by pradeeptosarkar** [comment]
@Rehan52004 assigned you different issue https://github.com/NSCC-BPIT/NSCC-BPIT-Website/issues/305

**Comment by pragyamishra56** [comment]
@pradeeptosarkar Sir, could you please assist me like when I changed the icon , I need guidance on how to view the main page of the project. Can you please specify where I can find this page and how to preview it during the process? Currently, I encounter a blank page issue, as shown in the screenshot
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/115208912/d6aa466c-d6ac-4321-aa49-5c71c042eb03)

**Comment by pradeeptosarkar** [comment]
you can have a look at https://github.com/NSCC-BPIT/NSCC-BPIT-Website#how-to-contribute as well

**Comment by pragyamishra56** [comment]
> did you do an "npm install" and "npm start"? @pragyamishra56

Yes Sir I did this

**Comment by pradeeptosarkar** [comment]
then open http://localhost:3000/ . you will see the project running

**Comment by pragyamishra56** [comment]
@pradeeptosarkar thank you Sir I'll try and give my best under your guidance

**Comment by pragyamishra56** [comment]
> @pradeeptosarkar Thank you Sir I'll try and give my best under your guidance



> then open http://localhost:3000/ . you will see the project running

@pradeeptosarkar Sir, when I opened the link you mentioned here, it appeared like this
![Screenshot 2023-10-11 123404](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/115208912/728867d2-6243-485a-b724-282d597d8582)

**Comment by pradeeptosarkar** [comment]
i guess there is some issue with your files. maybe some changes have got into them. you can start the whole process afresh. and follow https://github.com/NSCC-BPIT/NSCC-BPIT-Website#how-to-contribute line be line. It should not be a problem

**Comment by pragyamishra56** [comment]
@pradeeptosarkar Alright, sir, as you mentioned, I will follow the same instructions

**Comment by pragyamishra56** [comment]
@pradeeptosarkar Sir all done I created pull request

**Comment by pradeeptosarkar** [comment]
thanks for contributing @pragyamishra56

**Comment by pragyamishra56** [comment]
> thanks for contributing @pragyamishra56

@pradeeptosarkar Thanks to you Sir for assigning me to that issue
