### ISSUE TITLE
[Feature]: Add animation of mobile navbar

### ISSUE THREAD

**Issue by akash0708** [NSCC-BPIT/NSCC-BPIT-Website#337]
### Is your feature request related to a problem? Please describe.

The navbar appears suddenly without any animation.

### Describe the solution you'd like

I would add a subtle descending from top animation, which well help improve the user experience

**Comment by pradeeptosarkar** [comment]
go ahead @akash0708

**Comment by pradeeptosarkar** [comment]
@akash0708 need to close this issue
