### ISSUE TITLE
In the navbar contributing to the repository button should be available[Feature]: 

### ISSUE THREAD

**Issue by ayushjaswal** [NSCC-BPIT/NSCC-BPIT-Website#338]
### Is your feature request related to a problem? Please describe.

I wanted to contribute to this website, so while exploring I stumbled upon the problem that no where in the website is present a button i.e gateway to git repo. It is easier to find and contribute if the link to the repository is available in the website itself.

### Describe the solution you'd like

I would like to add a button in the navbar, through which one can navigate to our git hub repo and start contributing. This will make it easier for the contributor to
i) know that the website is open sourced,
ii) to navigate and contribute to git hub repository

**Comment by ayushjaswal** [comment]
I would like to be assigned this issue

**Comment by pradeeptosarkar** [comment]
go ahead @ayushjaswal

**Comment by ayushjaswal** [comment]
Pull Request submitted!

**Comment by pradeeptosarkar** [comment]
resolved
