### ISSUE TITLE
[Doc]: main to master

### ISSUE THREAD

**Issue by Rehan52004** [NSCC-BPIT/NSCC-BPIT-Website#345]
### Describe the bug

- [ ] Information addition regarding the newest change through a PR.
- [X] Typo error.
- [ ] New category addition.
- [ ] Refractoring sentences that make more sense.
- [ ] Fixing broken links.
- [ ] Refractors / reformating of the document.

**Comment by pradeeptosarkar** [comment]
@Rehan52004 where is the typor

**Comment by mnnkhndlwl** [comment]
it's a very small issue
