### ISSUE TITLE
[Feature]: Create a new page for Rust programming Language

### ISSUE THREAD

**Issue by piyushw0203** [NSCC-BPIT/NSCC-BPIT-Website#346]
### Describe the solution you'd like

include resources and information about Rust. pls assign

**Comment by pradeeptosarkar** [comment]
go ahead @piyushw0203

**Comment by pradeeptosarkar** [comment]
are you still working on this issue? @piyushw0203

**Comment by piyushw0203** [comment]
yes, I'll try to do it by today EOD

**Comment by tamago01** [comment]
I could do this too

**Comment by pradeeptosarkar** [comment]
@tamago01 assigned to you

**Comment by pradeeptosarkar** [comment]
closing this issue as of now
