### ISSUE TITLE
[Bug]: Resource cards not linked to resource pages

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#355]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/b6273526-0c0d-4656-86b7-7b9b6b69c4b7)

The resource cards are not connected to the resource pages. One should go to the respective resource page when they click on a particular card. All the pages are built and routed already. Someone might have tampered with the linking arrow button.

**Comment by piyushw0203** [comment]
I'm working on it.

**Comment by pradeeptosarkar** [comment]
@piyushw0203 I am doing it

**Comment by pradeeptosarkar** [comment]
resolved
