### ISSUE TITLE
'cursor-pointer' property not applicable for all social links .

### ISSUE THREAD

**Issue by the-shivam-gupta** [NSCC-BPIT/NSCC-BPIT-Website#364]
Some social link buttons lack the 'cursor: pointer' CSS property when hovered.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/6b14ca29-46fb-490c-a3e0-9b8a50d8b0c9)

**Comment by pradeeptosarkar** [comment]
go ahead @the-shivam-gupta
