### ISSUE TITLE
ContactUs page

### ISSUE THREAD

**Issue by the-shivam-gupta** [NSCC-BPIT/NSCC-BPIT-Website#365]
The text on the right, when there's no input provided, may not appear very interactive. 
Solution: It should be positioned below the Contact Us header.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/0b6014b2-3178-43e5-a1b8-7c87f022edfe)

**Comment by lohitkolluri** [comment]
Can i be assigned this issue?

**Comment by pradeeptosarkar** [comment]
resolved

**Comment by the-shivam-gupta** [comment]
If U would have assigned it to me I would have made it more attractive :)

**Comment by pradeeptosarkar** [comment]
@the-shivam-gupta if you have any thing more to add you can proceed

**Comment by the-shivam-gupta** [comment]
@pradeeptosarkar  I'm getting an error while running "npm start" on my system-
**Error: Cannot find module './range'**

**Comment by the-shivam-gupta** [comment]
It is showing the branch is already updated and the same error arises.

**Comment by pradeeptosarkar** [comment]
oh.! @mnnkhndlwl do you have anything to share?
