### ISSUE TITLE
[Feature]: Create the page for reinforcement learning

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#367]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/reinforcement-learning

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/5b9280a6-4108-4d4c-b96e-b5256ad4d633)

add the content and resources to this page

**Comment by piyushw0203** [comment]
can i work on this?

**Comment by pradeeptosarkar** [comment]
go ahead @piyushw0203

**Comment by sagarbee** [comment]
i want to work on this page,can i?

**Comment by pradeeptosarkar** [comment]
@sagarbee already assigned. we will open new issues soon

**Comment by sagarbee** [comment]
Ok sir thank you for response. actually I am participating in collabcode carnival and this is one of 10 project on which we have contribute. I would like to solve as many issues possible as I can 🙂.
