### ISSUE TITLE
[Feature]: Remove the Data Science card from AI/ML main page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#368]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/947ab4e4-49be-4b97-9970-7c1129dc8d02)

https://www.nsccbpit.tech/aiml

we don't need the data science card in the ai/ml page as we have a separate page for data science

**Comment by Mithilesh-create** [comment]
I would like to solve this issue . Please assign this to me .
