### ISSUE TITLE
[Feature]: add the content to tensor-flow page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#369]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/tensorflow

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/fe512c64-4fc6-431b-9145-7872a49cc015)

add the content and resources to this page

**Comment by prakartigoel24** [comment]
Please assign this to me

**Comment by pradeeptosarkar** [comment]
go ahead @prakartigoel24

**Comment by pradeeptosarkar** [comment]
resolved
