### ISSUE TITLE
[Feature]: add the content to pytorch page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#370]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/pytorch

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/ca8bc329-e949-4ef7-9e53-0ac162199caf)

add the content and resources to this page

**Comment by piyushw0203** [comment]
may i do this?

**Comment by pradeeptosarkar** [comment]
go ahead @piyushw0203

**Comment by pradeeptosarkar** [comment]
resolved
