### ISSUE TITLE
[Feature]: add the content scikit learn page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#371]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/scikit-learn

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/d66f3447-3d11-4507-9ffe-b434c231994d)

add the content and resources to this page

**Comment by Laxmankohar** [comment]
hey @pradeeptosarkar , I would like to work on this issue. Could you please assign it to me?

**Comment by pradeeptosarkar** [comment]
go ahead @Laxmankohar
