### ISSUE TITLE
[Feature]: add content to matplotlib page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#372]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/matplotlib

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/6df44ffa-4c3f-4f8c-9f7a-8536309f6d64)

add the content and resources to this page

**Comment by Laxmankohar** [comment]
Hey @pradeeptosarkar , I would like to work on this issue. Could you please assign it to me?

**Comment by pradeeptosarkar** [comment]
go ahead @Laxmankohar

**Comment by Laxmankohar** [comment]
Hey @pradeeptosarkar , Could you please check this?

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/73365025/342c5319-dc29-4929-9d24-06ff85b82fb4)

**Comment by pradeeptosarkar** [comment]
@Laxmankohar its good. you may now raise the PR

**Comment by pradeeptosarkar** [comment]
resolved
