### ISSUE TITLE
[Feature]: add content to numpy page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#373]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/numpy

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/8285852d-c80a-4de3-9b21-55bdf5f41870)

add the content and resources to this page

**Comment by prakartigoel24** [comment]
Please assign this to me

**Comment by pradeeptosarkar** [comment]
resolved
