### ISSUE TITLE
[Feature]: add content to pandas page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#374]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/pandas

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/ad5c66aa-c347-46dc-bbe5-ebe2a276180d)

add the content and resources to this page

**Comment by Laxmankohar** [comment]
Hey @pradeeptosarkar , Could you please check it?

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/73365025/027fbf86-143a-4e55-a8e6-17ff581ea706)

**Comment by pradeeptosarkar** [comment]
@Laxmankohar you may raise a PR its good
