### ISSUE TITLE
[Feature]: add content to keras page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#375]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/keras

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/22723c6c-8286-4263-ba44-0b94e98fda8c)

add the content and resources to this page

**Comment by piyushw0203** [comment]
can i work on this?

**Comment by pradeeptosarkar** [comment]
resolved
