### ISSUE TITLE
[Feature]: add content to the mlops page

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#376]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/mlops

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/0ededfbe-5b74-40ca-b078-51283ebd592c)

add the content and resources to this page

**Comment by sajithsojan** [comment]
please assign me to this

**Comment by pradeeptosarkar** [comment]
go ahead @sajithsojan

**Comment by pradeeptosarkar** [comment]
resolved
