### ISSUE TITLE
[Feature]: add content to mathematics page of data science section

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#377]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/mathematics

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/4c9ff944-cb9c-4261-8af0-6b5ebf28c4ea)

add the content and resources to this page

**Comment by gaudzispriyanshu** [comment]
assign me this

**Comment by pradeeptosarkar** [comment]
@gaudzispriyanshu go ahead

**Comment by pradeeptosarkar** [comment]
resolved
