### ISSUE TITLE
[Feature]: add content to statistics page under data science

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#378]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/Statistics

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/7890f833-7520-4dbb-958b-165ac5b2c509)

add the content and resources to this page

**Comment by Laxmankohar** [comment]
Hey @pradeeptosarkar , I would like to work on this issue. Could you please assign it to me?

**Comment by Laxmankohar** [comment]
Hey @mnnkhndlwl , Could you please check it?

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/73365025/98d163fb-84a5-41f0-805c-8694849e1cba)

**Comment by pradeeptosarkar** [comment]
@Laxmankohar its good. pls raise the PR

**Comment by Laxmankohar** [comment]
> @Laxmankohar its good. pls raise the PR

Ok. i will raise the PR by EOD.
