### ISSUE TITLE
[Feature]: add content to econometrics page under data science

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#379]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/econometrics

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/ed6b3208-a8b4-41a6-8d28-489459019436)

add the content and resources to this page

**Comment by saikiranpatil** [comment]
i would like to work on this, what resources should be added in this page?

**Comment by saikiranpatil** [comment]
> i would like to work on this, what resources should be added in this page?

@mnnkhndlwl 

WHAT RESOURCES SHOULD BE ADDED?
