### ISSUE TITLE
[Feature]: add python under data science

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#381]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/ad0ac6c8-4e7c-4aeb-b89b-ff283814f8c7)

in the data science page there is a card titled "python".

remove that card. insert a new card titled "python". then create the page as well and provide all resources for python such as documentations, youtube channels and courses

**Comment by sajithsojan** [comment]
please assign me to this task

**Comment by sajithsojan** [comment]
> please assign me to this task

i have changed the name coding to python

**Comment by sajithsojan** [comment]
> > please assign me to this task
> 
> i have changed the name coding to python

should i create a new page named python and add resources?

**Comment by pradeeptosarkar** [comment]
@

> > > please assign me to this task
> > 
> > 
> > i have changed the name coding to python
> 
> should i create a new page named python and add resources?

@sajithsojan yes

**Comment by pradeeptosarkar** [comment]
assigned

**Comment by pradeeptosarkar** [comment]
@sajithsojan you may have a look at the social media component page. in which we have displayed 3 youtube videos. maybe it will help.

and which link are you copying? to properly embed the videos, you should copy the "embed link" of the video and not the share link

**Comment by sajithsojan** [comment]
> @sajithsojan you may have a look at the social media component page. in which we have displayed 3 youtube videos. maybe it will help.
> 
> and which link are you copying? to properly embed the videos, you should copy the "embed link" of the video and not the share link

Ok thank you let me correct it

**Comment by pradeeptosarkar** [comment]
@sajithsojan have you raised a PR?

**Comment by sajithsojan** [comment]
> @sajithsojan have you raised a PR?

Ok I will raise a PR

**Comment by pradeeptosarkar** [comment]
resolved
