### ISSUE TITLE
[Feature]: add R under data science

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#382]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/9c12483e-335f-4ab5-bec0-efc7d0834f95)

in the data science page add a new card for "R programming language"
connect the card to a page and insert all resources to learn R programming such as youtube channels, tutorials and courses

**Comment by Wassaf001** [comment]
assign it to me.

**Comment by pradeeptosarkar** [comment]
resolved
