### ISSUE TITLE
[Feature]: create and connect the page for IoT Software Development

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#384]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/94559901-c4e5-4661-a9c9-34ed29510e80)

create the page for the concerned subdomain and insert all relevant resources such as tutorials, articles, youtube channels, videos and courses

**Comment by tiwari00ayush** [comment]
hey @pradeeptosarkar  , I would like to work on this issue. Could you please assign it to me?

**Comment by pradeeptosarkar** [comment]
go ahead @tiwari00ayush
