### ISSUE TITLE
[Feature]: create and connect the page for IoT Applications and Industry Specialization

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#386]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/b961e5db-a8dd-4235-a6d2-52bc84f030ef)

create the page for the concerned subdomain and insert all relevant resources such as tutorials, articles, youtube channels, videos and courses

**Comment by sajithsojan** [comment]
Please Assign me to this task

**Comment by pradeeptosarkar** [comment]
go ahead @sajithsojan

**Comment by pradeeptosarkar** [comment]
resolved
