### ISSUE TITLE
[Feature]: new page under devops for ansible

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#387]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/devops

create the page for the subject, connect it to the card. 

On the page provide all information and resources related to the concerned topic such as tutorials, documentation, youtube channels, articles, courses etc.

**Comment by Shruti700** [comment]
Can you assign this to me? @pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
assigned to @Shruti700
