### ISSUE TITLE
[Feature]: new page under devops for Gitlab CI

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#389]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/devops

create the page for the subject, connect it to the card. 

On the page provide all information and resources related to the concerned topic such as tutorials, documentation, youtube channels, articles, courses etc.

**Comment by Shu12388y** [comment]
@pradeeptosarkar can you assign this issue to me

**Comment by pradeeptosarkar** [comment]
go ahead @Shu12388y
