### ISSUE TITLE
[Feature]: new page under devops for heroku

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#390]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/devops

create the page for the subject, connect it to the card. 

On the page provide all information and resources related to the concerned topic such as tutorials, documentation, youtube channels, articles, courses etc.

**Comment by PabloSSena** [comment]
Hello, i'd like to work on this

**Comment by PabloSSena** [comment]
Hello i created a PR for this

**Comment by pradeeptosarkar** [comment]
resolved
