### ISSUE TITLE
[Feature]: new page under devops for oracle cloud

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#392]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/devops

create the page for the subject, connect it to the card. 

On the page provide all information and resources related to the concerned topic such as tutorials, documentation, youtube channels, articles, courses etc.

**Comment by vaibhavshah03** [comment]
I want to work on this issue assign me :)

**Comment by pradeeptosarkar** [comment]
@vaibhavshah03 go ahead

**Comment by pradeeptosarkar** [comment]
@vaibhavshah03 are you still working on this issue

**Comment by piyushw0203** [comment]
can i work on this?

**Comment by sagarbee** [comment]
@pradeeptosarkar , Please assign me this issue; I have successfully resolved similar ones before.

**Comment by pradeeptosarkar** [comment]
go ahead @sagarbee
