### ISSUE TITLE
[Feature]: new page under devops for google cloud platform

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#394]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/devops

create the page for the subject, connect it to the card. 

On the page provide all information and resources related to the concerned topic such as tutorials, documentation, youtube channels, articles, courses etc.

**Comment by pradeeptosarkar** [comment]
@Shruti700 we have open issues for them also here: https://github.com/NSCC-BPIT/NSCC-BPIT-Website/issues/388 https://github.com/NSCC-BPIT/NSCC-BPIT-Website/issues/387

**Comment by pradeeptosarkar** [comment]
do you want to work on google cloud page also?

**Comment by Shruti700** [comment]
Yeah sure you can assign me these tasks

**Comment by pradeeptosarkar** [comment]
@Shruti700 assigned to you

**Comment by pradeeptosarkar** [comment]
@Shruti700 you need to comment on the issues for ansible and terraform so that i can assign you those
