### ISSUE TITLE
[Feature]: add the page and card for solidity

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#395]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/21ef4896-7e3f-4d4b-ad14-ca3412496a65)

under the blockchain page, add a new card for solidity and connect it to a new page.

in the solidity page mention all resources and tools to learn solidity such as youtube channels, tutorials, courses documentations etc.

**Comment by gaudzispriyanshu** [comment]
Done with this

**Comment by pradeeptosarkar** [comment]
resolved
