### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ishan-nahid** [NSCC-BPIT/NSCC-BPIT-Website#401]
### Describe the bug

[https://www.nsccbpit.tech/webd](https://www.nsccbpit.tech/webd)

in this page , Django logo is not showing. 
can i fix it? 
![django](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/27049478/a3698f73-9b65-4b30-a4bb-c3654dc0ac01)

**Comment by pradeeptosarkar** [comment]
@ishan-nahid go ahead

**Comment by ishan-nahid** [comment]
@pradeeptosarkar check, review and marge with "hacktoberfest-accepted" label.
