### ISSUE TITLE
[Feature]:  Display a Pop-Up Message for Contact Us Page Error Message 

### ISSUE THREAD

**Issue by lohitkolluri** [NSCC-BPIT/NSCC-BPIT-Website#402]
### Describe the solution you'd like

A pop up message would look much better

**Comment by devesh711** [comment]
I figured out your feature correctly and ready to work on this, can you assign me this?

**Comment by pradeeptosarkar** [comment]
@devesh711 go ahead

**Comment by devesh711** [comment]
@pradeeptosarkar please Check and merge the Opened PR , also can you label this issue under hacktober fest.
