### ISSUE TITLE
[Bug]: Carousel buttons improvment 

### ISSUE THREAD

**Issue by akshaykaluse35** [NSCC-BPIT/NSCC-BPIT-Website#405]
### Describe the bug

Carousel buttons are not properly visible, we can make them more good

### Expected Behavior

It should be more clear to the users 

### Screenshot/ Video

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/69835893/1b6b1408-0014-400f-b868-ddf7fa913cbf)

### Desktop (please complete the following information)

Laptop
Ubuntu
firefox
118.0.2

**Comment by akshaykaluse35** [comment]
Please assign this issue with hacktober fest label

**Comment by pradeeptosarkar** [comment]
go ahead @akshaykaluse35

**Comment by Eufanzky** [comment]
Please, assign it to me.

**Comment by pradeeptosarkar** [comment]
resolved

**Comment by akshaykaluse35** [comment]
Sorry for late response, due to some college work i was not able to contribute. Please reopen this issue, So I'll make the carousel more beautiful.... Thank you
