### ISSUE TITLE
[Bug]: make checkbox list data persist in resourses page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#41]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/8565ff16-38c1-4147-bcfa-69200710662c)
currently this data of checkboxs are stored in localstorage which changes if we reload the page make it persist even if we reload page the data should remain unchanged 
you can use redux toolkit for it

**Comment by akssshh** [comment]
Hey @mnnkhndlwl Can i work on this?

**Comment by mnnkhndlwl** [comment]
Yeah bro @akssshh

**Comment by Baburao-sanivada** [comment]
Can i work on This?

**Comment by mnnkhndlwl** [comment]
@Baburao-sanivada already assigned to @akssshh 
you can check other issues to work on

**Comment by mnnkhndlwl** [comment]
@akssshh are you still working on this issue

**Comment by akssshh** [comment]
Yess

**Comment by mnnkhndlwl** [comment]
ok take your time if you are struck  somewhere or facing some problem you can contact me or @pradeeptosarkar

**Comment by akssshh** [comment]
Ok thanks!

**Comment by mnnkhndlwl** [comment]
hi bro are you still working on this issue

**Comment by akssshh** [comment]
Yes! @mnnkhndlwl

**Comment by mnnkhndlwl** [comment]
@akssshh you have taken a lot of time
