### ISSUE TITLE
[Feature]: Back to top button 

### ISSUE THREAD

**Issue by Nupur19nj** [NSCC-BPIT/NSCC-BPIT-Website#415]
### Is your feature request related to a problem? Please describe.

I need to scroll all the way to top again if i need to go to top!

### Describe the solution you'd like

I will create a button and if you click on that you'll again reach on the top of the page!

**Comment by pradeeptosarkar** [comment]
would you like to work on thi @Nupur19nj

**Comment by Nupur19nj** [comment]
Ya please assign me this under hacktober-accepted

**Comment by pradeeptosarkar** [comment]
go ahead @Nupur19nj
