### ISSUE TITLE
[Feature]: Add some content about web development before the roadmap component in resources page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#42]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/479271fd-0beb-4728-9607-ce2b594466c7)

**Comment by imnrb** [comment]
Can you assign me this?

**Comment by mnnkhndlwl** [comment]
@imnrb assigned you this  issue
