### ISSUE TITLE
[Bug]: Scrolling Malfunction on Brave Browser 

### ISSUE THREAD

**Issue by SAYUK09** [NSCC-BPIT/NSCC-BPIT-Website#422]
### Describe the bug

This issue only seems to be occurring on _Brave Browser_. (Works fine on Firefox)

**ISSUE:**
When scrolling up on the website, window is automatically taken scrolled down to the bottom.
This makes it impossible to stay or read any particular section.

The below attached gif would describe the issue clearly.

![NSCC](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/68416000/59c62692-9364-4835-bd7c-bd26b3a92940)

### To Reproduce

1. Open Brave Browser
2. Open any page of the [NSCC](https://www.nsccbpit.tech/events) website, expect the home page.

### Screenshot/ Video

![NSCC](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/68416000/65b62e67-6335-4de5-89b5-9eaa2202210e)

### Desktop (please complete the following information)

Device - Lenovo Thinkbook
OS -  Linux Ubuntu 22.04
Browser - Brave

**Comment by SAYUK09** [comment]
I would like to work futher on this issue, if possible.
@mnnkhndlwl @pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
go ahead @SAYUK09

**Comment by SAYUK09** [comment]
> go ahead @SAYUK09

Done. Here's the PR.
https://github.com/NSCC-BPIT/NSCC-BPIT-Website/pull/423

**Comment by pradeeptosarkar** [comment]
resolved
