### ISSUE TITLE
[Feature]: change the layout of project's page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#425]
### Is your feature request related to a problem? Please describe.

for reference 
[screen-capture.webm](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/246a159a-c29b-4400-89b2-619b93a8d48e)

**Comment by hemanth110702** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by hemanth110702** [comment]
Hey @mnnkhndlwl , I have kept the pull request can you please check it and say if there is any issue?

**Comment by Jatingupta9120** [comment]
please asign this issue to me under OSEN and Hacktoberfest
