### ISSUE TITLE
[Feature]: modify this resource page for different skills

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#43]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/98f95119-e03e-4396-bf20-9139386a7b31)

### Describe the solution you'd like

you just need to change the content of this page like first one is for web development and next you can add android development, ai/ml,ar/vr,data science and other tech domains

**Comment by mnnkhndlwl** [comment]
@keshav39 assigning you this issue

**Comment by anshulkumarx7** [comment]
Can i work on this issue?

**Comment by mnnkhndlwl** [comment]
@anshulkumarx7 assigned you this issue

**Comment by anshulkumarx7** [comment]
<img width="558" alt="image" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109407234/539bcc0a-54ed-45c0-aca6-eae36c756a9c">

**Comment by anshulkumarx7** [comment]
Assigned Work done.Generated pr
