### ISSUE TITLE
[Feature]: DevOps Topic-Link Integration

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#431]
### Is your feature request related to a problem? Please describe.

The current setup of our DevOps documentation website, https://www.nsccbpit.tech/devops, has a DevOps section that lists various topics. However, when users click on a specific topic, it doesn't redirect them to a detailed page for that topic. This can be confusing for users who want in-depth information on a particular subject.

### Describe the solution you'd like

I propose the creation of a new feature that enhances the user experience by allowing users to click on a specific DevOps topic, and upon clicking, they are automatically redirected to a dedicated and detailed page for that topic. This feature will streamline the navigation and improve the accessibility of information.

Specifically, the solution would include:

The development of individual detailed pages for each DevOps topic, linked to the corresponding topic in the DevOps section.
Adding clickable links to each topic listed in the DevOps section, directing users to the detailed page for that specific topic.
Ensuring that the design and layout of the detailed pages are user-friendly, providing comprehensive information, tutorials, documentation, links to YouTube channels, articles, courses, and any other resources related to the specific DevOps topic.

### Additional context

![Screenshot (71)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/5ff22f5f-9942-44b9-9926-96d3b165a9a7)
![Screenshot (72)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/0ea8c814-063c-4ac8-b437-4ef25b88ca44)

**Comment by pradeeptosarkar** [comment]
@sagarbee will you be creating new pages for those topics or just link to existing pages on the internet. According to that I will assign the difficulty tag to this issue

**Comment by sagarbee** [comment]
just link to existing pages on the internet

**Comment by pradeeptosarkar** [comment]
cool. go ahead
