### ISSUE TITLE
[Feature]: create the page for adobe and integrate it with uiux

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#432]
![Screenshot (73)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/328041f3-1c0e-4b97-ba75-f78c81702a68)

**Comment by pradeeptosarkar** [comment]
go ahead @sagarbee

**Comment by pradeeptosarkar** [comment]
resolved
