### ISSUE TITLE
[Feature]: Make a template page for projects

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#44]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/88907da5-2938-41c1-ba36-7a393cbd312a)

**Comment by kittoteja** [comment]
only I need to make template then assign me I can make it with html, css

**Comment by mnnkhndlwl** [comment]
@kittoteja it's react project can you work with react??

**Comment by kittoteja** [comment]
YES,please tell me more about this project

**Comment by mnnkhndlwl** [comment]
okay assigning you this issue

**Comment by mnnkhndlwl** [comment]
go through the project if you have any doubt please reach out to maintainers

**Comment by kittoteja** [comment]
After running it there are all instructions, and submitting stuff, Shoud I
remove all and make the template.

**Comment by mnnkhndlwl** [comment]
you only have to modify this page https://github.com/NSCC-BPIT/NSCC-BPIT-Website/blob/master/src/Pages/Projects/Projects.jsx

**Comment by kittoteja** [comment]
What change or features should I do??

**Comment by mnnkhndlwl** [comment]
bro just modify this page so that we can show case our projects here like a photo for project,project name,project github link,and project owner name

**Comment by mnnkhndlwl** [comment]
you can add this project as our first project

**Comment by mnnkhndlwl** [comment]
@kittoteja are still working on this issue

**Comment by kittoteja** [comment]
I need more time

**Comment by mnnkhndlwl** [comment]
ok no problem take your time

**Comment by mnnkhndlwl** [comment]
@kittoteja are you still working on this issue
