### ISSUE TITLE
[Bug]: html page layout under web development page->html

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#441]
### Describe the bug

I am submitting a request for a layout adjustment on our HTML web page. 
Specifically, the web page currently features sections for "Introduction," "Topics," and "Resources."
 We have identified a layout issue that needs to be addressed.

### Expected Behavior

The expected behavior is to have a well-organized and visually appealing layout for our web page. 
The "Introduction," "Topics," and "Resources" sections should be structured in a user-friendly and aesthetically pleasing manner.

### Screenshot/ Video

![Screenshot (81)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/ed7770c5-61c0-4672-a656-58b749c13f99)
![Screenshot (82)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/2a3fd601-6cc6-4afc-b88d-91570923758e)

**Comment by pradeeptosarkar** [comment]
go ahead @sagarbee
