### ISSUE TITLE
[Bug]: In css framework some images are not showing.

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#442]
### Describe the bug

I have encountered an issue with the CSS framework where some images are not displaying as expected.

### Expected Behavior

The expected behavior is that all images specified in the CSS framework should be displayed correctly.

### Screenshot/ Video

![Screenshot (83)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/16787e04-01ae-4f1c-b7ff-d57b1727d202)
![Screenshot (84)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/f04cf155-8201-4fed-8368-28b91ee37601)

**Comment by pradeeptosarkar** [comment]
go ahead @sagarbee . but now no more issues. work on the previous issues first
