### ISSUE TITLE
[Bug]: Enhancements for Topic Links and Integration

### ISSUE THREAD

**Issue by thanmaisai** [NSCC-BPIT/NSCC-BPIT-Website#444]
### Describe the bug

I've noticed a discrepancy in the current implementation regarding linking topics with their respective titles. When attempting to link topics, there seems to be an inconsistency that needs attention.

### To Reproduce

1.    Navigate to https://www.nsccbpit.tech/webd.
2.    Attempt to link a topic to its title.
3.    Observe the unexpected behavior or inconsistency.

### Expected Behavior

I expect the topic linking functionality to seamlessly integrate with the respective titles, providing a more user-friendly experience. This should enhance the overall navigation and organization of content.

### Screenshot/ Video

<img width="799" alt="Screenshot 2023-10-25 at 12 13 52 AM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91474486/3533b37d-e74b-49fa-b3c2-918e9228410c">

### Desktop (please complete the following information)

    Device: Laptop
    OS: MacOS
    Browser: Firefox

**Comment by thanmaisai** [comment]
Please assign me this issue, and do add the labels for the issue/PR raised in order to make it a valuable contribution for hacktoberfest 2023 and OSEN open source program.

**Comment by pradeeptosarkar** [comment]
go ahead @thanmaisai

**Comment by thanmaisai** [comment]
Hello @pradeeptosarkar, I've addressed the issue #450. Kindly review it and merge it with the appropriate tag.
