### ISSUE TITLE
[Bug]: Add some gap between team cards

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#45]
### Describe the bug

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/4f03853b-da6f-45d6-a86b-9314e5bdc3ea)
make sure everything is responsive

**Comment by bishwobista** [comment]
Can you assign this to me?

**Comment by mnnkhndlwl** [comment]
@bishwobista assigned
