### ISSUE TITLE
[Bug]:  Addressing Image Display Issues Across Different Screen Sizes

### ISSUE THREAD

**Issue by thanmaisai** [NSCC-BPIT/NSCC-BPIT-Website#453]
### Describe the bug

Images are not adapting appropriately to diverse screen sizes, causing display problems such as cropping or non-rendering.

### To Reproduce

1.  Open https://www.nsccbpit.tech on devices with different screen sizes.
2.  Observe image display issues.

### Expected Behavior

Implement responsive design principles, ensuring images adjust dynamically to different screen dimensions.

### Screenshot/ Video

<img width="1205" alt="Screenshot 2023-10-25 at 12 02 26 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91474486/3fb5abfa-be6d-447a-a80f-bd8ae4f4b463">

### Desktop (please complete the following information)

Device: Laptop
OS: MacOS
Browser: Firefox

**Comment by pradeeptosarkar** [comment]
go ahead @thanmaisai

**Comment by pradeeptosarkar** [comment]
@thanmaisai are you still working on thi sissue

**Comment by princechauhan23** [comment]
Hi, 
@pradeeptosarkar, got the issue, but need more clarity about your design principles.
