### ISSUE TITLE
[Bug]: Javascript Page Layout is not Align

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#457]
### Describe the bug

The project dashboard layout is misaligned, making navigation and interaction difficult.
I expect the JavaScript page layout in GitLab to align correctly and render all elements as intended.

### Expected Behavior

I expect the JavaScript page layout in GitLab to align correctly and render all elements as intended.

### Screenshot/ Video

![Screenshot (98)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/2aa22652-f197-41b4-9553-8c3b5708236e)
![Screenshot (99)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/e03dd85e-a8a6-4074-8b15-82278aa1d3b7)

**Comment by gaudzispriyanshu** [comment]
assign me this

**Comment by sagarbee** [comment]
@pradeeptosarkar's, I hope this message finds you well. I'd like to request the assignment of this issue to me. I initially raised this issue with the intention of resolving it, and I believe I can provide a timely and efficient solution.

I appreciate @gaudzispriyanshu's interest in contributing to this issue, but given my prior involvement and familiarity with the problem, I would like to continue working on it.

@gaudzispriyanshu, thank you for your willingness to help. If there are other issues or opportunities to collaborate, I'd be more than happy to work together on those.

I kindly request your permission to be assigned to this issue so that I can proceed with the resolution. Your consideration is greatly appreciated.

Thank you for your time and understanding.

Best regards,
@sagarbee

**Comment by gaudzispriyanshu** [comment]
@sagarbee ohh! it's okay
