### ISSUE TITLE
[Feature]:For Team page requesting the implementation of a "scroll to top" feature on our website. This feature will be built using JavaScript for scroll behavior and will be styled with Tailwind CSS. 

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#469]
### Is your feature request related to a problem? Please describe.

#Feature Request: Scroll to Top Button
#Implementation: This feature will be developed using JavaScript and styled with Tailwind CSS.

### Describe the solution you'd like

The button will appear when the user has scrolled down a certain distance (e.g., 200 pixels) to indicate its availability.
Clicking the button will trigger a smooth scrolling animation that takes the user back to the top of the page.

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/6d247c70-69c3-432d-8b71-35ef099e8148

**Comment by adi-ray** [comment]
Could you please assign me this issue @sagarbee ?

**Comment by pradeeptosarkar** [comment]
@sagarbee go ahead

**Comment by sagarbee** [comment]
Hi @pradeeptosarkar sir,

I'd like to clarify a situation with Pull Request #474  

Pull Request #474 doesn't have a specific label, but it contains the changes that address the issue #469. These changes have been successfully merged into the master branch.

I apologize for any confusion, and I want to ensure that you are aware that the changes from issue #469 have been incorporated in Pull Request #474.

Please review Pull Request #474, which contains the resolved issue #469, and let me know if any further action is required.

Thank you for your time and understanding.

Best regards,
@sagarbee

**Comment by pradeeptosarkar** [comment]
got it
