### ISSUE TITLE
[Feature]: Create a page for  "Sorting" resource page under competitive programming . 

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#471]
### Describe the solution you'd like

This page will serve as the hub for different types of sorting algorithms.

![Screenshot (129)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/f93ac465-67ba-4e27-b72d-f8295349ed42)

**Comment by pradeeptosarkar** [comment]
@sagarbee go ahead
