### ISSUE TITLE
[Feature]: Create a page for "Searching Algorithms" resource page under competitive programming 

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#472]
### Describe the solution you'd like

This page will serve as the hub for different types of searching algorithms.

![Screenshot (129)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/46a90960-b973-40ee-8aab-c370acb4a97e)

**Comment by pradeeptosarkar** [comment]
@sagarbee go ahead
