### ISSUE TITLE
[Feature]: Create a page for "Dynamic Programming" resource page under competitive programming 

### ISSUE THREAD

**Issue by sagarbee** [NSCC-BPIT/NSCC-BPIT-Website#473]
### Describe the solution you'd like

This page will serve as the hub for different types of Dynamic Programming algorithms.

![Screenshot (129)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/65588552/f7b1cd26-32b4-445e-9bf6-f87114adc613)

**Comment by pradeeptosarkar** [comment]
@sagarbee go ahead
