### ISSUE TITLE
[Bug]: Make the homepage team carousel start sliding only when it is in focus.

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#48]
### Describe the bug

There is a team carousel by the headline "Meet the Team 2023-24". The carousel starts rotating every time the page loads/reloads. So by the time a visitor reaches that section after reading the previous sections, the carousel has already passed a few names. Ideally, when a visitor reaches the carousel portion, he/she should first see the President/Vice-President and so on. i.e. the carousel should start rotating only when it is in focus and stop when it is not.

### Screenshot/ Video

Current situation:

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/97f69cca-ce50-4588-859a-71d1eee5c987)

Ideal situation:

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/8c4c49a3-32ac-469f-ba23-670fc63d6281)
 when a visitor reaches the carousel after scrolling, he/she should first see the President and so on.!

**Comment by abhisheksharm-3** [comment]
hi, can i work on this?

**Comment by pradeeptosarkar** [comment]
sure. go ahead.!

**Comment by pradeeptosarkar** [comment]
assigned to you buddy.!

**Comment by Baburao-sanivada** [comment]
Can i work on this?

**Comment by pradeeptosarkar** [comment]
@Baburao-sanivada already assigned. We will soon open more issues.!

**Comment by Baburao-sanivada** [comment]
ok

**Comment by abhisheksharm-3** [comment]
hey @pradeeptosarkar , should i do something like,  if carousel is not in viewport it should pause but when it is, it should scroll, or only do it once like user loads the page, comes to carousel and then carousel starts and should not stop again even when user is not in viewport

**Comment by abhisheksharm-3** [comment]
carousel is not in viewport*

**Comment by pradeeptosarkar** [comment]
yes @abhisheksharm-3 it should scroll only when in viewport otherwise paused.!

**Comment by pradeeptosarkar** [comment]
merged @abhisheksharm-3 . thanks for contributing :)
