### ISSUE TITLE
[Design]: Removing scrollbar from testimonials and adding a border for a card-like look  

### ISSUE THREAD

**Issue by Rahul-1611** [NSCC-BPIT/NSCC-BPIT-Website#481]
### Is your feature request related to a problem? Please describe.

Some of the testimonials have an overflow which makes the scrollbar appear , although the scrollbar is styled nicely it does not appear in beside every testimonial , which makes it look like a bug or a design inconsistency.
<img width="1061" alt="Screenshot 2023-10-31 at 15 51 46" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/80812276/934837cc-cab5-437d-9e6a-aebba6a2a497">

### Describe the solution you'd like

The best solution would be to remove the scrollbar completely so that the design looks consistent and to add a extra point of view where each card stands out we can add a border to it .
It would look somewhat like this:
<img width="1269" alt="Screenshot 2023-10-31 at 17 06 29" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/80812276/d83ddd63-ab6c-49a2-970a-3b9b15e2301a">

### Describe alternatives you've considered

Alternatives solutions I tried was 
1. To add a box-shadow inside the text area so that it looks like there's more text below
Problem : It appears on every box , so even if the testimonial is short it looks like there is something below and also a was unable to make shadow that is only coming from one side with enough blur on it.

2. To add a right border to text only which creates a sort of separation between divs 
Problem : Cards look much better visually as compared to right border only

### Additional context

If you can assign me this issue I would be delighted to send a pull request .
Also this would be my first pull request ever so I wanted to work on something small.

I would like to implement the above design I suggested in the above image.

**Comment by pradeeptosarkar** [comment]
go ahead @Rahul-1611
