### ISSUE TITLE
[Feature]: Hover effect while cursor is on SEND button

### ISSUE THREAD

**Issue by adi-ray** [NSCC-BPIT/NSCC-BPIT-Website#484]
### Is your feature request related to a problem? Please describe.

1. There is no hover effect while cursor is on Send message button in Contact Us section. 
2. Also, message text area is resizable . It should be fixed.

### Describe the solution you'd like

1. A proper hover effect which is compatible and aligns with the web page theme will be applied .
2. Setting up the resize property none for message textarea field.

### Additional context

Please assign me this issue under hacktoberfest label.

**Comment by pradeeptosarkar** [comment]
go ahead @adi-ray

**Comment by pradeeptosarkar** [comment]
@adi-ray are you still working on this issue

**Comment by codePerfect7** [comment]
Thanks for merging. Can you mark this issue as closed

**Comment by pradeeptosarkar** [comment]
resolved
