### ISSUE TITLE
Navbar appearance.

### ISSUE THREAD

**Issue by the-shivam-gupta** [NSCC-BPIT/NSCC-BPIT-Website#485]
I noticed that the previous navigation bar didn't look very good and was split into two separate divs for the left and right sides. To improve its appearance, I made some changes to the navigation bar. Here are the modifications that I applied on my end:

Image 1:

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/47cfa9da-6966-4dd1-bc58-ed2a988bcd60)

Image 2:

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/8664a44d-b225-44a4-b894-abd40a6506d1)

**Comment by the-shivam-gupta** [comment]
@pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
assigned to you @the-shivam-gupta
