### ISSUE TITLE
Content Overlap Problem.

### ISSUE THREAD

**Issue by the-shivam-gupta** [NSCC-BPIT/NSCC-BPIT-Website#489]
Clicking the hamburger menu, the displayed list overlaps with the content of the home page, adversely affecting the site's overall impression.

- **Proposed solution**: Blurring the content behind the displayed lists when the hamburger menu is opened.

Content Overlap Image:

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/698e53ee-dd44-402b-938c-ef7c1a64622f)

**Comment by pradeeptosarkar** [comment]
go ahead @the-shivam-gupta
