### ISSUE TITLE
Responsiveness for mobile devices.

### ISSUE THREAD

**Issue by the-shivam-gupta** [NSCC-BPIT/NSCC-BPIT-Website#493]
Some of the content does not respond properly on mobile devices from 320px to 400px.

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/48b3e741-cc1c-4910-8e06-ea56bad7d31e

**Comment by pradeeptosarkar** [comment]
@the-shivam-gupta go ahead
