### ISSUE TITLE
Add left margin in Keras resource page.

### ISSUE THREAD

**Issue by DikshaDhasmana** [NSCC-BPIT/NSCC-BPIT-Website#496]
### Describe the bug

Left Margin is needed to be added in the Keras resource page.

### To Reproduce

1. Go to the Nav Bar.
2. Click on 'Resources'.
3. Click on 'AI ML'.
4. Go to Frameworks and click on 'Keras'.

### Expected Behavior

The page is supposed to have uniform margins.

### Screenshot/ Video

![image_2023-11-13_190135756](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/123383817/230afc85-196d-44e0-a6a5-bfea5efe1b63)

### Desktop (please complete the following information)

Device - HP Laptop
OS - Windows 11
Browser - Opera GX

**Comment by pradeeptosarkar** [comment]
@DikshaDhasmana go ahead

**Comment by sankettank66** [comment]
can I fix this issue? @pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
@sankettank66 already assigned to @DikshaDhasmana
