### ISSUE TITLE
Navigation: 'Connect with Us' Opens in a New Page.

### ISSUE THREAD

**Issue by the-shivam-gupta** [NSCC-BPIT/NSCC-BPIT-Website#499]
To enhance user experience, consider redirecting the "Connect with us" link to open in a new page. 

It is necessary to open this page in a new tab:

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/e442a322-9eef-49e6-b561-3e937c0b30a4)

**Comment by the-shivam-gupta** [comment]
@pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
go ahead @the-shivam-gupta
