### ISSUE TITLE
[Feature]: Add more content on webd page 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#50]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/6a5bee5e-2dc2-4be8-bf4f-4b500daf3605)

### Describe the solution you'd like

currently we have only frontend in which we have only shown html,csss and javascript 
you have to add more content in this page such as after javascript you can add css frameworks/libraries , js frameworks,hosting websites 
And additionaly you can add content for backend also
Please attach some screenshots while making pr

**Comment by IamSudhir-Kumar** [comment]
Can you assign this to me!! Please

**Comment by mnnkhndlwl** [comment]
@IamSudhir-Kumar assigned you  this issue

**Comment by IamSudhir-Kumar** [comment]
Here's a screenshot of the changes ;-
![frontend](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/112376748/9e78f3e0-350a-48d7-a732-4d5a5bb1761e)

![backend](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/112376748/31e20c96-85d1-4912-aee9-71ba01253148)

Is there anything I should improve or change.

**Comment by mnnkhndlwl** [comment]
@pradeeptosarkar bro please check this pr and if everything is fine merge the pr

**Comment by pradeeptosarkar** [comment]
resolved.!
