### ISSUE TITLE
[z-index]: Back to top button.

### ISSUE THREAD

**Issue by the-shivam-gupta** [NSCC-BPIT/NSCC-BPIT-Website#503]
I have come across a minute error in the code that the z-index of the "**back-to-top**" button is not greater due to which when it comes under the contact section the image prevents the button from being clicked.

**Solution**: Adding a z-index to the button higher than the entire web page.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/5fab85cd-9fa8-41c5-b8c9-abd95b7dfb1e)

**Comment by pradeeptosarkar** [comment]
go for it @the-shivam-gupta
