### ISSUE TITLE
[Feature]: add more resources on js page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#51]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/f30b77c5-715a-4eb6-baff-fa32dd250a64)

**Comment by HarjjotSinghh** [comment]
can you please assign me this issue and also describe the issue further.

**Comment by mnnkhndlwl** [comment]
@HarjjotSinghh assigned you this issue
