### ISSUE TITLE
[Feature]: make separate page for css 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#52]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/27e78b14-e7da-4b27-866a-1e619bd8cf56)
just like we have this page for js make a separate page for css also
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/4d181513-097f-43ec-8f33-b88e61f05b52)

**Comment by Chetax** [comment]
@mnnkhndlwl  i want to work on this issue please assign it to me

**Comment by mnnkhndlwl** [comment]
@Chetax assigned you this issue

**Comment by mnnkhndlwl** [comment]
@Chetax are you still working on this issue

**Comment by Chetax** [comment]
Sorry Sir,I Am Not Working On This Issue Right Now.

**Comment by mnnkhndlwl** [comment]
@Chetax i guess i have to assign it to someone else then

**Comment by Chetax** [comment]
Yes Sir Sorry For inconvenience

**Comment by keshav39** [comment]
kindly close this issue if u think its resolved @mnnkhndlwl

**Comment by pradeeptosarkar** [comment]
resolved
