### ISSUE TITLE
[Feature]: make a separate page for html

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#53]
### Is your feature request related to a problem? Please describe.

just like we have a separate page for js https://www.nsccbpit.tech/js 
make a separate page for html also

**Comment by bkpecho** [comment]
Hey! I would like to work on this issue.

**Comment by mnnkhndlwl** [comment]
@bkpecho assigned you this issue

**Comment by keshav39** [comment]
[Suggesstion] : there are no links to redirect to the JS page or the HTML page. And in the resource page, we have the web dev card. So, there can be link to the JS and HTML pages in the page that web dev card refers to. #75
