### ISSUE TITLE
[Feature]: Enhance Website Aesthetics with Customized Scrollbar

### ISSUE THREAD

**Issue by akhilender-bongirwar** [NSCC-BPIT/NSCC-BPIT-Website#56]
### Is your feature request related to a problem? Please describe.

The current state of the website has a simple/default scrollbar.

### Describe the solution you'd like

 To enhance visibility, we can add a customized scrollbar for a more appealing appearance.

### Describe alternatives you've considered

Implementing a customized scrollbar to improve the website's aesthetics and user experience.

### Additional context

Customizing the scrollbar can include changing its color, size to make it more visually appealing and in line with the website's overall style.

**Comment by pradeeptosarkar** [comment]
would you like to work on this? @akhilender-bongirwar

**Comment by Adityacodesinpython** [comment]
Hey I believe I can do this. Can you assign this to me?

**Comment by akhilender-bongirwar** [comment]
> would you like to work on this? @akhilender-bongirwar

Yeah @pradeeptosarkar : )

**Comment by pradeeptosarkar** [comment]
sure @akhilender-bongirwar go ahead.! assigned to you

**Comment by pradeeptosarkar** [comment]
sorry @Adityacodesinpython 😕 since the issue was originally opened by him. We will open more issues dw. :)

**Comment by pradeeptosarkar** [comment]
@akhilender-bongirwar I think the feature is not working as expected. Kindly check

**Comment by akhilender-bongirwar** [comment]
@pradeeptosarkar, the scrollbar feature is working fine. Please check the below video.

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/112749383/39d17beb-2161-45c1-90bc-c66bc8dc23f7

**Comment by pradeeptosarkar** [comment]
@mnnkhndlwl @keshav39 can you pls confirm, maybe its an issue on my side

**Comment by akhilender-bongirwar** [comment]
@pradeeptosarkar, I have noticed that it is not being shown on the main website - https://www.nsccbpit.tech/ even after merging my PR. Maybe I can give it a try to place the custom scrollbar css code in the index.css in the src folder so that it even renders on the main website IMP.

**Comment by pradeeptosarkar** [comment]
yep @akhilender-bongirwar go ahead. but do test it once locally as well

**Comment by pradeeptosarkar** [comment]
merged and done. thanks for contributing @akhilender-bongirwar

**Comment by akhilender-bongirwar** [comment]
@pradeeptosarkar, yeah I was right about going to index.css instead of index.html. It worked. Could you please add hacktoberfestaccepted label : ).
