### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by keshav39** [NSCC-BPIT/NSCC-BPIT-Website#61]
### Is your feature request related to a problem? Please describe.

The navbar on the site does not stick to the top and as the website involves a lot of scrolling, to redirect to another page, we have to scroll back to the top to change the page.
So having a sticky navbar will make redirection faster for the users.

### Describe the solution you'd like

The solutions can have the css of position fixed and top 0 but this will result in the body of the webpage getting pushed upwards. Also the navbar has a transparent background so you will have to add a corresponding background to it and push the body of the webpage down.

**Comment by rupamsutar** [comment]
Hey there Keshav, 

I am new to open source, but  I can solve the problem ! 
May I ?

**Comment by Vinoth-git-17** [comment]
In mobile view the hamburger menu and logo is not align properly !

**Comment by keshav39** [comment]
> In mobile view the hamburger menu and logo is not align properly ! kindly fix that too @keshav39

r u referring to this 👇

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/345453b9-211d-49cc-895e-59ab487c6fea)

**Comment by Vinoth-git-17** [comment]
> > In mobile view the hamburger menu and logo is not align properly ! kindly fix that too @keshav39
> 
> r u referring to this 👇
> 
> ![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/345453b9-211d-49cc-895e-59ab487c6fea)
> 

Yeah bro

**Comment by keshav39** [comment]
> > > In mobile view the hamburger menu and logo is not align properly ! kindly fix that too @keshav39
> > 
> > 
> > r u referring to this 👇
> > ![image](https://user-images.githubusercontent.com/91420120/271828974-345453b9-211d-49cc-895e-59ab487c6fea.png)
> 
> Yeah bro

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/5c4912a9-053d-4ce6-9b79-ccfd78488150)

is this alright?

**Comment by Vinoth-git-17** [comment]
> > > > In mobile view the hamburger menu and logo is not align properly ! kindly fix that too @keshav39
> > > 
> > > 
> > > r u referring to this 👇
> > > ![image](https://user-images.githubusercontent.com/91420120/271828974-345453b9-211d-49cc-895e-59ab487c6fea.png)
> > 
> > Yeah bro
> 
> ![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/5c4912a9-053d-4ce6-9b79-ccfd78488150)
> 
> is this alright?

Fine Can you make the hamburger little larger it should be perfect
 Thanks.
