### ISSUE TITLE
[Bug]: Project Tab doesn't look good or in sync with rest of the pages

### ISSUE THREAD

**Issue by Ritesh-Dabral** [NSCC-BPIT/NSCC-BPIT-Website#64]
### Describe the bug

On navigating to https://www.nsccbpit.tech and clicking on the *Projects* tab, a new component loads which is not full screen and looks out of sync compared to other tabs. 

### To Reproduce

- Go to https://www.nsccbpit.tech
- Click on the *Projects* tab

### Expected Behavior

The project page should take entire screen to keep the UX consistent

### Screenshot/ Video

`Mobile View`
<img width="379" alt="Screenshot 2023-10-01 at 2 14 40 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/36252036/9506fa4e-a52a-4e84-91bb-91603c8a7d6e">

`Desktop View`
<img width="1185" alt="Screenshot 2023-10-01 at 2 14 24 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/36252036/2ffe0330-4ced-4e4d-86c8-a86d7a5242f3">

### Desktop (please complete the following information)

Device - [All]
OS - [All]
Browser [All]
Version [All]

**Comment by Ritesh-Dabral** [comment]
@mnnkhndlwl Kindly review this bug and assign this to me

**Comment by mnnkhndlwl** [comment]
someone is already working  on this page
