### ISSUE TITLE
[Bug]: Overlapping of content in Desktop

### ISSUE THREAD

**Issue by Vinoth-git-17** [NSCC-BPIT/NSCC-BPIT-Website#65]
### Describe the bug

Desktop: Event, Testimonials  and contact section at the end are overlapping eachother.

Mobile: There is no problem in mobile view

### To Reproduce

>Go to Event,  Testimonials, Contact
>Give the margin to  Section for desktop
>All set

### Screenshot/ Video

![bug2](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/111376793/280db703-c040-4048-b293-2f73b8a3da57)
![bug1](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/111376793/19c2f409-6e30-4558-937b-080aa9bdf5ee)

### Desktop (please complete the following information)

Device - Laptop Hp
OS - Windows
Browser - Chrome

**Comment by Vinoth-git-17** [comment]
@mnnkhndlwl Review the bug and assign it to me

**Comment by mnnkhndlwl** [comment]
assigned but make sure it's responsive for every screen
