### ISSUE TITLE
[Feature]: Custom 404 page

### ISSUE THREAD

**Issue by Ritesh-Dabral** [NSCC-BPIT/NSCC-BPIT-Website#67]
### Is your feature request related to a problem? Please describe.

The issue is that, on entering an unknown path, the page returned is completely blank. Which hinders the UX

<img width="1192" alt="Screenshot 2023-10-01 at 2 48 04 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/36252036/fc5e26a3-2188-44f3-9ecf-70c16466288f">

### Describe the solution you'd like

I would like to add a custom 404 page on the application to make it more appealing

### Describe alternatives you've considered

An alternative solution of this would be to always redirect to the home page if no coding effort is required on the 404 page, although a custom 404 page is always a good solution to handle multiple use cases

**Comment by Ritesh-Dabral** [comment]
@mnnkhndlwl Please assign this issue to me

**Comment by pradeeptosarkar** [comment]
@Ritesh-Dabral sure buddy you may go ahead.

**Comment by Ritesh-Dabral** [comment]
<img width="1139" alt="Screenshot 2023-10-01 at 4 35 30 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/36252036/ffcf59c4-691e-42f9-91ee-5f781fc39447">
<img width="373" alt="Screenshot 2023-10-01 at 4 35 02 PM" src="https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/36252036/9ed5b8df-b53d-49dc-a9c5-8bf98ec28e26">


@pradeeptosarkar Kindly verify the design. Post that I will raise PR

**Comment by pradeeptosarkar** [comment]
merged and done. thanks for contributing @Ritesh-Dabral
