### ISSUE TITLE
[Feature]: Add page for android development 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#76]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/c40c75cb-5ca2-4ad6-823f-6a709c81c58c)
just like this page for webd make a separate page for android development

**Comment by Gauravtb2253** [comment]
Hello , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

**Comment by joshijoe05** [comment]
Hello, I would like to work on this.
Can you assign me this issue

**Comment by pradeeptosarkar** [comment]
@Gauravtb2253 assigned to you
