### ISSUE TITLE
[Feature]: Add a page for AI/ml 

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#77]
### Is your feature request related to a problem? Please describe.

we should go to that page from resource page take example from https://www.nsccbpit.tech/webd

**Comment by joshijoe05** [comment]
Hello I would like to work on this. Can you assign me this issue

**Comment by Gauravtb2253** [comment]
Hello , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

**Comment by pradeeptosarkar** [comment]
@joshijoe05 assigned to you. please have a look at the web dev page and make something similar for ai/ml

**Comment by pradeeptosarkar** [comment]
@joshijoe05 are you working on this issue?

**Comment by joshijoe05** [comment]
@pradeeptosarkar Yes Im working on this

**Comment by joshijoe05** [comment]
Please unassign me as Frontend is not my cup of tea !

**Comment by pradeeptosarkar** [comment]
no worries @joshijoe05

**Comment by pradeeptosarkar** [comment]
resolved, thanks for contributing @Gauravtb2253
