### ISSUE TITLE
[Feature]: add a page for ar/vr

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#79]

**Comment by vamsi-spoidey7** [comment]
hey i would like to work on this as part of hacktoberfest 2023. please assign to me

**Comment by pradeeptosarkar** [comment]
@vamsi-spoidey7 assigned to you

**Comment by vamsi-spoidey7** [comment]
please unassign me from this issue

**Comment by Gauravtb2253** [comment]
Hello , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

**Comment by mnnkhndlwl** [comment]
@Gauravtb2253 assigned you this task

**Comment by pradeeptosarkar** [comment]
@Gauravtb2253 successfully resolved. Thanks for contributing
