### ISSUE TITLE
[Feature]: add a page for internet of things

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#80]

**Comment by the-shivam-gupta** [comment]
Could you please provide more details on what needs to be included in the IoT section?

**Comment by pradeeptosarkar** [comment]
@the-shivam-gupta yeah sure. we are thinking of providing domain specific roadmaps for all domains. currently the web dev one is under construction. once its live you may get a better idea. feel free to suggest your own design as well

**Comment by the-shivam-gupta** [comment]
In this, I have provided a link that contains various resources for understanding different topics.

From what I understand, it seems like you are referring to something like this.

Referenced from: https://www.linkshub.dev

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/109647722/675a9a5d-b982-4618-a3d9-3b873a1e225f)

**Comment by pradeeptosarkar** [comment]
@the-shivam-gupta sort of yes. have a look at the web dev page here https://www.nsccbpit.tech/webd

**Comment by the-shivam-gupta** [comment]
Sure, I'll create a design and inform you if it meets your approval.

**Comment by mnnkhndlwl** [comment]
@the-shivam-gupta assigned you this issue

**Comment by pradeeptosarkar** [comment]
@the-shivam-gupta are you still working on this issue?

**Comment by the-shivam-gupta** [comment]
Yes

**Comment by Rehan52004** [comment]
It is very easy task, I done it in 3 - 4 hours.
