### ISSUE TITLE
[Feature]: add a card for blockchain development in resource page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#81]

**Comment by vamsi-spoidey7** [comment]
Hai i would love to wok on this as a part of hacktober fest 2023. Please assign to me

**Comment by Gauravtb2253** [comment]
Hello , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

**Comment by pradeeptosarkar** [comment]
@vamsi-spoidey7 assigned to you
