### ISSUE TITLE
[Feature]: add a  card for competitive programming in resource page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#82]

**Comment by bishwobista** [comment]
Hey, assign me this issue

**Comment by mnnkhndlwl** [comment]
@bishwobista assigned you this issue

**Comment by bishwobista** [comment]
What do we want to write in the card?

**Comment by Gauravtb2253** [comment]
Hello , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

**Comment by pradeeptosarkar** [comment]
hi @Gauravtb2253 pls take up other issues. this one is done.
