### ISSUE TITLE
[Feature]: add a card for devops in resource page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#83]

**Comment by vk-44** [comment]
I would like to work on this. Please assign me.

**Comment by Gauravtb2253** [comment]
Hello , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

**Comment by pradeeptosarkar** [comment]
@Gauravtb2253 assigned to you

**Comment by pradeeptosarkar** [comment]
resolved
