### ISSUE TITLE
[Feature]: add relevant icons to each skill in resources page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#84]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/79ab38b9-9f6f-4f8b-b645-bce07b3b1576)

**Comment by Yogeshp0012** [comment]
Please assign me this issue.

**Comment by Akshay9607** [comment]
hey, i have added the icons , can you please review and merge this.

**Comment by Gauravtb2253** [comment]
Hello , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.
