### ISSUE TITLE
[Bug]: checkbox card in JS page and resources in HTML page

### ISSUE THREAD

**Issue by keshav39** [NSCC-BPIT/NSCC-BPIT-Website#91]
### Describe the bug

the checkboxes in the JS page need Improvement(refer the HTML page for the same) and the amount of resources in HTML page can be increased(refer to the JS page)

### To Reproduce

- go to the resources page
- click on the arrow in the web dev card
- scroll to look for tech stack card(html, css, js, etc.)
- open html page and js page respectively to look for the issue

### Expected Behavior

- The checkbox cards on HTML and JS page should look similar
- HTML page will have more resources

### Screenshot/ Video

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/ea72f68a-8133-4a6e-be12-559c8f305915)

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/e2abc4cc-3ccf-4b61-bda0-717642aef782)

too few resources(to compare see JS page)
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/91420120/91e6c57f-8296-4af8-bcc9-24623f4f1bf3)

### Desktop (please complete the following information)

Device - [All]
OS - [All]
Browser [All]
Version [All]

**Comment by Anish-Sarawgi** [comment]
Can you assign it to me.

**Comment by vk-44** [comment]
Hi, Can I work on this issue.

**Comment by pradeeptosarkar** [comment]
resolved, thanks for contributing @vk-44
