### ISSUE TITLE
[Feature]: Create the page for Competitive Programming 

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#93]
### Is your feature request related to a problem? Please describe.

from the resources page, on clicking on the competitive programming card, the user must be directed to a new page for CP.
Take example from https://www.nsccbpit.tech/webd 
the resources home page is at: https://www.nsccbpit.tech/resources

**Comment by HarjjotSinghh** [comment]
please assign me this :)

**Comment by mnnkhndlwl** [comment]
@HarjjotSinghh are you still working on this issue

**Comment by HarjjotSinghh** [comment]
> @HarjjotSinghh are you still working on this issue

@mnnkhndlwl yes, it will be done within 1-2 hours

**Comment by mnnkhndlwl** [comment]
okay take your time
