### ISSUE TITLE
[Feature]: Create new page for DevOps

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#94]
### Is your feature request related to a problem? Please describe.

from the resources page, on clicking on the devops card, the user must be directed to a new page for devops.
Take example from https://www.nsccbpit.tech/webd
the resources home page is at: https://www.nsccbpit.tech/resources

**Comment by Ritesh-Dabral** [comment]
@pradeeptosarkar Kindly assign this to me

**Comment by pradeeptosarkar** [comment]
resolved. thanks for contributing @Ritesh-Dabral :)
