### ISSUE TITLE
[Feature]: change reactjs to "choose a framework" in webd page make a separate page for that just like we have a separate page for javascript

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#96]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/68c32c95-32f0-458f-8880-09083517dc8b)
in choose a framework you can give introduction about different frontend frameworks like angular,reactjs,svelte and any other of your choice and resources for them also

**Comment by HarjjotSinghh** [comment]
if it is possible for a single person to have more than one task assigned, then I would like to take this up as well

**Comment by mnnkhndlwl** [comment]
@HarjjotSinghh no bro we want more and more people to contribute so one issue at a time

**Comment by pawas108ram** [comment]
I would like to work on this

**Comment by pradeeptosarkar** [comment]
@pawas108ram assigned
