### ISSUE TITLE
[Bug]: Form validation

### ISSUE THREAD

**Issue by raunakgiri21** [NSCC-BPIT/NSCC-BPIT-Website#97]
### Describe the bug

Contact Form gets submitted even with empty input fields.

### To Reproduce

1. Scroll down to contact form.
2. Keep the form input empty.
3. Click on submit.

### Expected Behavior

On submitting the empty form, warning message should be displayed.

### Screenshot/ Video

https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/53823257/6387b3ff-b53e-4088-8bdf-b962ff1b7c45

### Additional context

I want to try fixing this bug.

**Comment by HarjjotSinghh** [comment]
can you assign this to me please :)
