### ISSUE TITLE
[Feature]: change netlify to deployment in webd page and make a separate page for that just like we have a separate page for javascript

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#98]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/56715a97-0755-41b3-836b-40056158c4e9)
in deployment page you can give an introduction about what is deployment and different ways we can deploy our websites

**Comment by krishpatel023** [comment]
Can I work on it? Please assign it to me.

**Comment by mnnkhndlwl** [comment]
@krishpatel023 assigned you this issue

**Comment by pradeeptosarkar** [comment]
@krishpatel023 are you still working on this issue?

**Comment by krishpatel023** [comment]
Yes I am working on it. @pradeeptosarkar

**Comment by mnnkhndlwl** [comment]
@krishpatel023 are you building the deployment page???

**Comment by pradeeptosarkar** [comment]
will raise a fresh issue
